### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory
  commentId: T:Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory
  id: OpenAIClientSettingsFactory
  parent: Glitch9.AIDevKit.OpenAI
  children:
  - Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSerializerSettings
  - Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSettings
  langs:
  - csharp
  - vb
  name: OpenAIClientSettingsFactory
  nameWithType: OpenAIClientSettingsFactory
  fullName: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory
  type: Class
  source:
    id: OpenAIClientSettingsFactory
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/OpenAI/Client/OpenAI.cs
    startLine: 11
  namespace: Glitch9.AIDevKit.OpenAI
  syntax:
    content: 'public class OpenAIClientSettingsFactory : AIClientSettingsFactory'
    content.vb: Public Class OpenAIClientSettingsFactory Inherits AIClientSettingsFactory
  inheritance:
  - System.Object
  - Glitch9.AIDevKit.Client.AIClientSettingsFactory
  inheritedMembers:
  - Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
- uid: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSettings
  commentId: M:Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSettings
  id: CreateSettings
  parent: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory
  langs:
  - csharp
  - vb
  name: CreateSettings()
  nameWithType: OpenAIClientSettingsFactory.CreateSettings()
  fullName: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSettings()
  type: Method
  source:
    id: CreateSettings
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/OpenAI/Client/OpenAI.cs
    startLine: 13
  namespace: Glitch9.AIDevKit.OpenAI
  example: []
  syntax:
    content: protected override CRUDClientSettings CreateSettings()
    return:
      type: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
    content.vb: Protected Overrides Function CreateSettings() As CRUDClientSettings
  overridden: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  overload: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSettings*
- uid: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSerializerSettings
  commentId: M:Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSerializerSettings
  id: CreateSerializerSettings
  parent: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory
  langs:
  - csharp
  - vb
  name: CreateSerializerSettings()
  nameWithType: OpenAIClientSettingsFactory.CreateSerializerSettings()
  fullName: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSerializerSettings()
  type: Method
  source:
    id: CreateSerializerSettings
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/OpenAI/Client/OpenAI.cs
    startLine: 33
  namespace: Glitch9.AIDevKit.OpenAI
  example: []
  syntax:
    content: protected override AIClientSerializerSettings CreateSerializerSettings()
    return:
      type: Glitch9.AIDevKit.Client.AIClientSerializerSettings
    content.vb: Protected Overrides Function CreateSerializerSettings() As AIClientSerializerSettings
  overridden: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  overload: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSerializerSettings*
references:
- uid: Glitch9.AIDevKit.OpenAI
  commentId: N:Glitch9.AIDevKit.OpenAI
  href: Glitch9.html
  name: Glitch9.AIDevKit.OpenAI
  nameWithType: Glitch9.AIDevKit.OpenAI
  fullName: Glitch9.AIDevKit.OpenAI
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.OpenAI
    name: OpenAI
    href: Glitch9.AIDevKit.OpenAI.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.OpenAI
    name: OpenAI
    href: Glitch9.AIDevKit.OpenAI.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  commentId: T:Glitch9.AIDevKit.Client.AIClientSettingsFactory
  parent: Glitch9.AIDevKit.Client
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html
  name: AIClientSettingsFactory
  nameWithType: AIClientSettingsFactory
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  name: Create()
  nameWithType: AIClientSettingsFactory.Create()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
    name: Create
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
    name: Create
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Client
  commentId: N:Glitch9.AIDevKit.Client
  href: Glitch9.html
  name: Glitch9.AIDevKit.Client
  nameWithType: Glitch9.AIDevKit.Client
  fullName: Glitch9.AIDevKit.Client
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  name: CreateSettings()
  nameWithType: AIClientSettingsFactory.CreateSettings()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
    name: CreateSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
    name: CreateSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  - name: (
  - name: )
- uid: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSettings*
  commentId: Overload:Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSettings
  href: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.html#Glitch9_AIDevKit_OpenAI_OpenAIClientSettingsFactory_CreateSettings
  name: CreateSettings
  nameWithType: OpenAIClientSettingsFactory.CreateSettings
  fullName: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSettings
- uid: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
  commentId: T:Glitch9.IO.Networking.RESTApi.CRUDClientSettings
  parent: Glitch9.IO.Networking.RESTApi
  name: CRUDClientSettings
  nameWithType: CRUDClientSettings
  fullName: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
- uid: Glitch9.IO.Networking.RESTApi
  commentId: N:Glitch9.IO.Networking.RESTApi
  href: Glitch9.html
  name: Glitch9.IO.Networking.RESTApi
  nameWithType: Glitch9.IO.Networking.RESTApi
  fullName: Glitch9.IO.Networking.RESTApi
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.IO
    name: IO
    href: Glitch9.IO.html
  - name: .
  - uid: Glitch9.IO.Networking
    name: Networking
    href: Glitch9.IO.Networking.html
  - name: .
  - uid: Glitch9.IO.Networking.RESTApi
    name: RESTApi
    href: Glitch9.IO.Networking.RESTApi.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.IO
    name: IO
    href: Glitch9.IO.html
  - name: .
  - uid: Glitch9.IO.Networking
    name: Networking
    href: Glitch9.IO.Networking.html
  - name: .
  - uid: Glitch9.IO.Networking.RESTApi
    name: RESTApi
    href: Glitch9.IO.Networking.RESTApi.html
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  name: CreateSerializerSettings()
  nameWithType: AIClientSettingsFactory.CreateSerializerSettings()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
    name: CreateSerializerSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
    name: CreateSerializerSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  - name: (
  - name: )
- uid: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSerializerSettings*
  commentId: Overload:Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSerializerSettings
  href: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.html#Glitch9_AIDevKit_OpenAI_OpenAIClientSettingsFactory_CreateSerializerSettings
  name: CreateSerializerSettings
  nameWithType: OpenAIClientSettingsFactory.CreateSerializerSettings
  fullName: Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory.CreateSerializerSettings
- uid: Glitch9.AIDevKit.Client.AIClientSerializerSettings
  commentId: T:Glitch9.AIDevKit.Client.AIClientSerializerSettings
  parent: Glitch9.AIDevKit.Client
  href: Glitch9.AIDevKit.Client.AIClientSerializerSettings.html
  name: AIClientSerializerSettings
  nameWithType: AIClientSerializerSettings
  fullName: Glitch9.AIDevKit.Client.AIClientSerializerSettings
