### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.AIDevKitSettings
  commentId: T:Glitch9.AIDevKit.AIDevKitSettings
  id: AIDevKitSettings
  parent: Glitch9.AIDevKit
  children:
  - Glitch9.AIDevKit.AIDevKitSettings.CheckForModelUpdatesOnStartup
  - Glitch9.AIDevKit.AIDevKitSettings.DefaultEMB
  - Glitch9.AIDevKit.AIDevKitSettings.DefaultIMG
  - Glitch9.AIDevKit.AIDevKitSettings.DefaultLLM
  - Glitch9.AIDevKit.AIDevKitSettings.DefaultMOD
  - Glitch9.AIDevKit.AIDevKitSettings.DefaultSTT
  - Glitch9.AIDevKit.AIDevKitSettings.DefaultTTS
  - Glitch9.AIDevKit.AIDevKitSettings.EditorOutputPath
  - Glitch9.AIDevKit.AIDevKitSettings.LogLevel
  - Glitch9.AIDevKit.AIDevKitSettings.ProjectContext
  - Glitch9.AIDevKit.AIDevKitSettings.PromptHistoryOnRuntime
  - Glitch9.AIDevKit.AIDevKitSettings.RequestTimeout
  - Glitch9.AIDevKit.AIDevKitSettings.RuntimeOutputPath
  langs:
  - csharp
  - vb
  name: AIDevKitSettings
  nameWithType: AIDevKitSettings
  fullName: Glitch9.AIDevKit.AIDevKitSettings
  type: Class
  source:
    id: AIDevKitSettings
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 7
  namespace: Glitch9.AIDevKit
  syntax:
    content: 'public class AIDevKitSettings : ScriptableResource<AIDevKitSettings>'
    content.vb: Public Class AIDevKitSettings Inherits ScriptableResource(Of AIDevKitSettings)
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.AIDevKitSettings.RuntimeOutputPath
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.RuntimeOutputPath
  id: RuntimeOutputPath
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: RuntimeOutputPath
  nameWithType: AIDevKitSettings.RuntimeOutputPath
  fullName: Glitch9.AIDevKit.AIDevKitSettings.RuntimeOutputPath
  type: Property
  source:
    id: RuntimeOutputPath
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 40
  namespace: Glitch9.AIDevKit
  summary: Default path for runtime downloads, used in dynamically updating or adding resources at runtime.
  example: []
  syntax:
    content: public static string RuntimeOutputPath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property RuntimeOutputPath As String
  overload: Glitch9.AIDevKit.AIDevKitSettings.RuntimeOutputPath*
- uid: Glitch9.AIDevKit.AIDevKitSettings.EditorOutputPath
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.EditorOutputPath
  id: EditorOutputPath
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: EditorOutputPath
  nameWithType: AIDevKitSettings.EditorOutputPath
  fullName: Glitch9.AIDevKit.AIDevKitSettings.EditorOutputPath
  type: Property
  source:
    id: EditorOutputPath
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 56
  namespace: Glitch9.AIDevKit
  summary: Default path where editor-specific assets are downloaded, commonly used in Unity projects.
  example: []
  syntax:
    content: public static string EditorOutputPath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property EditorOutputPath As String
  overload: Glitch9.AIDevKit.AIDevKitSettings.EditorOutputPath*
- uid: Glitch9.AIDevKit.AIDevKitSettings.LogLevel
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.LogLevel
  id: LogLevel
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: LogLevel
  nameWithType: AIDevKitSettings.LogLevel
  fullName: Glitch9.AIDevKit.AIDevKitSettings.LogLevel
  type: Property
  source:
    id: LogLevel
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 76
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static RESTLogLevel LogLevel { get; }
    parameters: []
    return:
      type: RESTLogLevel
    content.vb: Public Shared ReadOnly Property LogLevel As RESTLogLevel
  overload: Glitch9.AIDevKit.AIDevKitSettings.LogLevel*
- uid: Glitch9.AIDevKit.AIDevKitSettings.RequestTimeout
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.RequestTimeout
  id: RequestTimeout
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: RequestTimeout
  nameWithType: AIDevKitSettings.RequestTimeout
  fullName: Glitch9.AIDevKit.AIDevKitSettings.RequestTimeout
  type: Property
  source:
    id: RequestTimeout
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 77
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static int RequestTimeout { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared ReadOnly Property RequestTimeout As Integer
  overload: Glitch9.AIDevKit.AIDevKitSettings.RequestTimeout*
- uid: Glitch9.AIDevKit.AIDevKitSettings.ProjectContext
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.ProjectContext
  id: ProjectContext
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: ProjectContext
  nameWithType: AIDevKitSettings.ProjectContext
  fullName: Glitch9.AIDevKit.AIDevKitSettings.ProjectContext
  type: Property
  source:
    id: ProjectContext
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 78
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static ProjectContext ProjectContext { get; }
    parameters: []
    return:
      type: Glitch9.AIDevKit.ProjectContext
    content.vb: Public Shared ReadOnly Property ProjectContext As ProjectContext
  overload: Glitch9.AIDevKit.AIDevKitSettings.ProjectContext*
- uid: Glitch9.AIDevKit.AIDevKitSettings.CheckForModelUpdatesOnStartup
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.CheckForModelUpdatesOnStartup
  id: CheckForModelUpdatesOnStartup
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: CheckForModelUpdatesOnStartup
  nameWithType: AIDevKitSettings.CheckForModelUpdatesOnStartup
  fullName: Glitch9.AIDevKit.AIDevKitSettings.CheckForModelUpdatesOnStartup
  type: Property
  source:
    id: CheckForModelUpdatesOnStartup
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 79
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static bool CheckForModelUpdatesOnStartup { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared ReadOnly Property CheckForModelUpdatesOnStartup As Boolean
  overload: Glitch9.AIDevKit.AIDevKitSettings.CheckForModelUpdatesOnStartup*
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultLLM
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.DefaultLLM
  id: DefaultLLM
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: DefaultLLM
  nameWithType: AIDevKitSettings.DefaultLLM
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultLLM
  type: Property
  source:
    id: DefaultLLM
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 80
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static string DefaultLLM { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property DefaultLLM As String
  overload: Glitch9.AIDevKit.AIDevKitSettings.DefaultLLM*
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultIMG
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.DefaultIMG
  id: DefaultIMG
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: DefaultIMG
  nameWithType: AIDevKitSettings.DefaultIMG
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultIMG
  type: Property
  source:
    id: DefaultIMG
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 81
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static string DefaultIMG { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property DefaultIMG As String
  overload: Glitch9.AIDevKit.AIDevKitSettings.DefaultIMG*
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultTTS
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.DefaultTTS
  id: DefaultTTS
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: DefaultTTS
  nameWithType: AIDevKitSettings.DefaultTTS
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultTTS
  type: Property
  source:
    id: DefaultTTS
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 82
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static string DefaultTTS { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property DefaultTTS As String
  overload: Glitch9.AIDevKit.AIDevKitSettings.DefaultTTS*
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultSTT
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.DefaultSTT
  id: DefaultSTT
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: DefaultSTT
  nameWithType: AIDevKitSettings.DefaultSTT
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultSTT
  type: Property
  source:
    id: DefaultSTT
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 83
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static string DefaultSTT { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property DefaultSTT As String
  overload: Glitch9.AIDevKit.AIDevKitSettings.DefaultSTT*
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultEMB
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.DefaultEMB
  id: DefaultEMB
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: DefaultEMB
  nameWithType: AIDevKitSettings.DefaultEMB
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultEMB
  type: Property
  source:
    id: DefaultEMB
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 84
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static string DefaultEMB { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property DefaultEMB As String
  overload: Glitch9.AIDevKit.AIDevKitSettings.DefaultEMB*
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultMOD
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.DefaultMOD
  id: DefaultMOD
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: DefaultMOD
  nameWithType: AIDevKitSettings.DefaultMOD
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultMOD
  type: Property
  source:
    id: DefaultMOD
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 85
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static string DefaultMOD { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property DefaultMOD As String
  overload: Glitch9.AIDevKit.AIDevKitSettings.DefaultMOD*
- uid: Glitch9.AIDevKit.AIDevKitSettings.PromptHistoryOnRuntime
  commentId: P:Glitch9.AIDevKit.AIDevKitSettings.PromptHistoryOnRuntime
  id: PromptHistoryOnRuntime
  parent: Glitch9.AIDevKit.AIDevKitSettings
  langs:
  - csharp
  - vb
  name: PromptHistoryOnRuntime
  nameWithType: AIDevKitSettings.PromptHistoryOnRuntime
  fullName: Glitch9.AIDevKit.AIDevKitSettings.PromptHistoryOnRuntime
  type: Property
  source:
    id: PromptHistoryOnRuntime
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/AIDevKitSettings.cs
    startLine: 86
  namespace: Glitch9.AIDevKit
  syntax:
    content: public static bool PromptHistoryOnRuntime { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared ReadOnly Property PromptHistoryOnRuntime As Boolean
  overload: Glitch9.AIDevKit.AIDevKitSettings.PromptHistoryOnRuntime*
references:
- uid: Glitch9.AIDevKit
  commentId: N:Glitch9.AIDevKit
  href: Glitch9.html
  name: Glitch9.AIDevKit
  nameWithType: Glitch9.AIDevKit
  fullName: Glitch9.AIDevKit
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.AIDevKitSettings.RuntimeOutputPath*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.RuntimeOutputPath
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_RuntimeOutputPath
  name: RuntimeOutputPath
  nameWithType: AIDevKitSettings.RuntimeOutputPath
  fullName: Glitch9.AIDevKit.AIDevKitSettings.RuntimeOutputPath
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Glitch9.AIDevKit.AIDevKitSettings.EditorOutputPath*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.EditorOutputPath
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_EditorOutputPath
  name: EditorOutputPath
  nameWithType: AIDevKitSettings.EditorOutputPath
  fullName: Glitch9.AIDevKit.AIDevKitSettings.EditorOutputPath
- uid: Glitch9.AIDevKit.AIDevKitSettings.LogLevel*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.LogLevel
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_LogLevel
  name: LogLevel
  nameWithType: AIDevKitSettings.LogLevel
  fullName: Glitch9.AIDevKit.AIDevKitSettings.LogLevel
- uid: RESTLogLevel
  commentId: '!:RESTLogLevel'
  isExternal: true
  name: RESTLogLevel
  nameWithType: RESTLogLevel
  fullName: RESTLogLevel
- uid: Glitch9.AIDevKit.AIDevKitSettings.RequestTimeout*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.RequestTimeout
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_RequestTimeout
  name: RequestTimeout
  nameWithType: AIDevKitSettings.RequestTimeout
  fullName: Glitch9.AIDevKit.AIDevKitSettings.RequestTimeout
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Glitch9.AIDevKit.AIDevKitSettings.ProjectContext*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.ProjectContext
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_ProjectContext
  name: ProjectContext
  nameWithType: AIDevKitSettings.ProjectContext
  fullName: Glitch9.AIDevKit.AIDevKitSettings.ProjectContext
- uid: Glitch9.AIDevKit.ProjectContext
  commentId: T:Glitch9.AIDevKit.ProjectContext
  parent: Glitch9.AIDevKit
  href: Glitch9.AIDevKit.ProjectContext.html
  name: ProjectContext
  nameWithType: ProjectContext
  fullName: Glitch9.AIDevKit.ProjectContext
- uid: Glitch9.AIDevKit.AIDevKitSettings.CheckForModelUpdatesOnStartup*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.CheckForModelUpdatesOnStartup
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_CheckForModelUpdatesOnStartup
  name: CheckForModelUpdatesOnStartup
  nameWithType: AIDevKitSettings.CheckForModelUpdatesOnStartup
  fullName: Glitch9.AIDevKit.AIDevKitSettings.CheckForModelUpdatesOnStartup
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultLLM*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.DefaultLLM
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_DefaultLLM
  name: DefaultLLM
  nameWithType: AIDevKitSettings.DefaultLLM
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultLLM
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultIMG*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.DefaultIMG
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_DefaultIMG
  name: DefaultIMG
  nameWithType: AIDevKitSettings.DefaultIMG
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultIMG
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultTTS*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.DefaultTTS
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_DefaultTTS
  name: DefaultTTS
  nameWithType: AIDevKitSettings.DefaultTTS
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultTTS
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultSTT*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.DefaultSTT
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_DefaultSTT
  name: DefaultSTT
  nameWithType: AIDevKitSettings.DefaultSTT
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultSTT
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultEMB*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.DefaultEMB
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_DefaultEMB
  name: DefaultEMB
  nameWithType: AIDevKitSettings.DefaultEMB
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultEMB
- uid: Glitch9.AIDevKit.AIDevKitSettings.DefaultMOD*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.DefaultMOD
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_DefaultMOD
  name: DefaultMOD
  nameWithType: AIDevKitSettings.DefaultMOD
  fullName: Glitch9.AIDevKit.AIDevKitSettings.DefaultMOD
- uid: Glitch9.AIDevKit.AIDevKitSettings.PromptHistoryOnRuntime*
  commentId: Overload:Glitch9.AIDevKit.AIDevKitSettings.PromptHistoryOnRuntime
  href: Glitch9.AIDevKit.AIDevKitSettings.html#Glitch9_AIDevKit_AIDevKitSettings_PromptHistoryOnRuntime
  name: PromptHistoryOnRuntime
  nameWithType: AIDevKitSettings.PromptHistoryOnRuntime
  fullName: Glitch9.AIDevKit.AIDevKitSettings.PromptHistoryOnRuntime
