### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1
  commentId: T:Glitch9.AIDevKit.Client.AIClientSettings`1
  id: AIClientSettings`1
  parent: Glitch9.AIDevKit.Client
  children:
  - Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey
  - Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey
  - Glitch9.AIDevKit.Client.AIClientSettings`1.apiKey
  - Glitch9.AIDevKit.Client.AIClientSettings`1.encryptApiKey
  - Glitch9.AIDevKit.Client.AIClientSettings`1.encryptedApiKey
  - Glitch9.AIDevKit.Client.AIClientSettings`1.oldApiKey
  langs:
  - csharp
  - vb
  name: AIClientSettings<TSelf>
  nameWithType: AIClientSettings<TSelf>
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>
  type: Class
  source:
    id: AIClientSettings
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClientSettings.cs
    startLine: 11
  namespace: Glitch9.AIDevKit.Client
  summary: >-
    Base class for AI client settings.

    This class is used to store API keys and other settings related to AI clients.
  example: []
  syntax:
    content: 'public abstract class AIClientSettings<TSelf> : ScriptableResource<TSelf> where TSelf : AIClientSettings<TSelf>'
    typeParameters:
    - id: TSelf
      description: ''
    content.vb: Public MustInherit Class AIClientSettings(Of TSelf As AIClientSettings(Of TSelf)) Inherits ScriptableResource(Of TSelf)
  inheritance:
  - System.Object
  derivedClasses:
  - Glitch9.AIDevKit.ElevenLabs.ElevenLabsSettings
  - Glitch9.AIDevKit.Google.GenerativeAISettings
  - Glitch9.AIDevKit.Mubert.MubertSettings
  - Glitch9.AIDevKit.OpenAI.OpenAISettings
  - Glitch9.AIDevKit.OpenRouter.OpenRouterSettings
  nameWithType.vb: AIClientSettings(Of TSelf)
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf)
  name.vb: AIClientSettings(Of TSelf)
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.oldApiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings`1.oldApiKey
  id: oldApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings`1
  langs:
  - csharp
  - vb
  name: oldApiKey
  nameWithType: AIClientSettings<TSelf>.oldApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.oldApiKey
  type: Field
  source:
    id: oldApiKey
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClientSettings.cs
    startLine: 14
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: protected string oldApiKey
    return:
      type: System.String
    content.vb: Protected oldApiKey As String
  nameWithType.vb: AIClientSettings(Of TSelf).oldApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).oldApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.encryptedApiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings`1.encryptedApiKey
  id: encryptedApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings`1
  langs:
  - csharp
  - vb
  name: encryptedApiKey
  nameWithType: AIClientSettings<TSelf>.encryptedApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.encryptedApiKey
  type: Field
  source:
    id: encryptedApiKey
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClientSettings.cs
    startLine: 15
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: protected string encryptedApiKey
    return:
      type: System.String
    content.vb: Protected encryptedApiKey As String
  nameWithType.vb: AIClientSettings(Of TSelf).encryptedApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).encryptedApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.encryptApiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings`1.encryptApiKey
  id: encryptApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings`1
  langs:
  - csharp
  - vb
  name: encryptApiKey
  nameWithType: AIClientSettings<TSelf>.encryptApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.encryptApiKey
  type: Field
  source:
    id: encryptApiKey
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClientSettings.cs
    startLine: 16
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: protected bool encryptApiKey
    return:
      type: System.Boolean
    content.vb: Protected encryptApiKey As Boolean
  nameWithType.vb: AIClientSettings(Of TSelf).encryptApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).encryptApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.apiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings`1.apiKey
  id: apiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings`1
  langs:
  - csharp
  - vb
  name: apiKey
  nameWithType: AIClientSettings<TSelf>.apiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.apiKey
  type: Field
  source:
    id: apiKey
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClientSettings.cs
    startLine: 17
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: protected ApiKey apiKey
    return:
      type: Glitch9.AIDevKit.ApiKey
    content.vb: Protected apiKey As ApiKey
  nameWithType.vb: AIClientSettings(Of TSelf).apiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).apiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey
  id: GetApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings`1
  langs:
  - csharp
  - vb
  name: GetApiKey()
  nameWithType: AIClientSettings<TSelf>.GetApiKey()
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.GetApiKey()
  type: Method
  source:
    id: GetApiKey
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClientSettings.cs
    startLine: 22
  namespace: Glitch9.AIDevKit.Client
  summary: Retrieves the API key.
  example: []
  syntax:
    content: public string GetApiKey()
    return:
      type: System.String
    content.vb: Public Function GetApiKey() As String
  overload: Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey*
  nameWithType.vb: AIClientSettings(Of TSelf).GetApiKey()
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).GetApiKey()
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey
  id: HasApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings`1
  langs:
  - csharp
  - vb
  name: HasApiKey()
  nameWithType: AIClientSettings<TSelf>.HasApiKey()
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.HasApiKey()
  type: Method
  source:
    id: HasApiKey
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClientSettings.cs
    startLine: 27
  namespace: Glitch9.AIDevKit.Client
  summary: Checks if the API key is set.
  example: []
  syntax:
    content: public virtual bool HasApiKey()
    return:
      type: System.Boolean
    content.vb: Public Overridable Function HasApiKey() As Boolean
  overload: Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey*
  nameWithType.vb: AIClientSettings(Of TSelf).HasApiKey()
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).HasApiKey()
references:
- uid: Glitch9.AIDevKit.Client
  commentId: N:Glitch9.AIDevKit.Client
  href: Glitch9.html
  name: Glitch9.AIDevKit.Client
  nameWithType: Glitch9.AIDevKit.Client
  fullName: Glitch9.AIDevKit.Client
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Glitch9.AIDevKit.ApiKey
  commentId: T:Glitch9.AIDevKit.ApiKey
  parent: Glitch9.AIDevKit
  href: Glitch9.AIDevKit.ApiKey.html
  name: ApiKey
  nameWithType: ApiKey
  fullName: Glitch9.AIDevKit.ApiKey
- uid: Glitch9.AIDevKit
  commentId: N:Glitch9.AIDevKit
  href: Glitch9.html
  name: Glitch9.AIDevKit
  nameWithType: Glitch9.AIDevKit
  fullName: Glitch9.AIDevKit
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey*
  commentId: Overload:Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_GetApiKey
  name: GetApiKey
  nameWithType: AIClientSettings<TSelf>.GetApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.GetApiKey
  nameWithType.vb: AIClientSettings(Of TSelf).GetApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).GetApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey*
  commentId: Overload:Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_HasApiKey
  name: HasApiKey
  nameWithType: AIClientSettings<TSelf>.HasApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.HasApiKey
  nameWithType.vb: AIClientSettings(Of TSelf).HasApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).HasApiKey
