### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings
  commentId: T:Glitch9.AIDevKit.ElevenLabs.VoiceSettings
  id: VoiceSettings
  parent: Glitch9.AIDevKit.ElevenLabs
  children:
  - Glitch9.AIDevKit.ElevenLabs.VoiceSettings.SimilarityBoost
  - Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Speed
  - Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Stability
  - Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Style
  - Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseSpeakerBoost
  - Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseStyleExaggeration
  langs:
  - csharp
  - vb
  name: VoiceSettings
  nameWithType: VoiceSettings
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings
  type: Class
  source:
    id: VoiceSettings
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/ElevenLabs/Models/Voice/Submodels/VoiceSettings.cs
    startLine: 4
  namespace: Glitch9.AIDevKit.ElevenLabs
  syntax:
    content: public class VoiceSettings
    content.vb: Public Class VoiceSettings
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Stability
  commentId: P:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Stability
  id: Stability
  parent: Glitch9.AIDevKit.ElevenLabs.VoiceSettings
  langs:
  - csharp
  - vb
  name: Stability
  nameWithType: VoiceSettings.Stability
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Stability
  type: Property
  source:
    id: Stability
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/ElevenLabs/Models/Voice/Submodels/VoiceSettings.cs
    startLine: 11
  namespace: Glitch9.AIDevKit.ElevenLabs
  summary: >-
    Optional. Determines how stable the voice is and the randomness between each generation.

    Lower values introduce broader emotional range for the voice.

    Higher values can result in a monotonous voice with limited emotion.
  example: []
  syntax:
    content: public double? Stability { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property Stability As Double?
  overload: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Stability*
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.SimilarityBoost
  commentId: P:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.SimilarityBoost
  id: SimilarityBoost
  parent: Glitch9.AIDevKit.ElevenLabs.VoiceSettings
  langs:
  - csharp
  - vb
  name: SimilarityBoost
  nameWithType: VoiceSettings.SimilarityBoost
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.SimilarityBoost
  type: Property
  source:
    id: SimilarityBoost
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/ElevenLabs/Models/Voice/Submodels/VoiceSettings.cs
    startLine: 16
  namespace: Glitch9.AIDevKit.ElevenLabs
  summary: Optional. Determines how closely the AI should adhere to the original voice when attempting to replicate it.
  example: []
  syntax:
    content: public double? SimilarityBoost { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property SimilarityBoost As Double?
  overload: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.SimilarityBoost*
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Style
  commentId: P:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Style
  id: Style
  parent: Glitch9.AIDevKit.ElevenLabs.VoiceSettings
  langs:
  - csharp
  - vb
  name: Style
  nameWithType: VoiceSettings.Style
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Style
  type: Property
  source:
    id: Style
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/ElevenLabs/Models/Voice/Submodels/VoiceSettings.cs
    startLine: 23
  namespace: Glitch9.AIDevKit.ElevenLabs
  summary: >-
    Optional. Determines the style exaggeration of the voice.

    This setting attempts to amplify the style of the original speaker.

    This setting consumes additional computational resources and might increase latency if set to anything other than 0.
  example: []
  syntax:
    content: public double? Style { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property Style As Double?
  overload: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Style*
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseSpeakerBoost
  commentId: P:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseSpeakerBoost
  id: UseSpeakerBoost
  parent: Glitch9.AIDevKit.ElevenLabs.VoiceSettings
  langs:
  - csharp
  - vb
  name: UseSpeakerBoost
  nameWithType: VoiceSettings.UseSpeakerBoost
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseSpeakerBoost
  type: Property
  source:
    id: UseSpeakerBoost
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/ElevenLabs/Models/Voice/Submodels/VoiceSettings.cs
    startLine: 29
  namespace: Glitch9.AIDevKit.ElevenLabs
  summary: >-
    Optional. This setting boosts the similarity to the original speaker.

    Using this setting requires a slightly higher computational load, which in turn increases latency.
  example: []
  syntax:
    content: public bool? UseSpeakerBoost { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public Property UseSpeakerBoost As Boolean?
  overload: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseSpeakerBoost*
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Speed
  commentId: P:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Speed
  id: Speed
  parent: Glitch9.AIDevKit.ElevenLabs.VoiceSettings
  langs:
  - csharp
  - vb
  name: Speed
  nameWithType: VoiceSettings.Speed
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Speed
  type: Property
  source:
    id: Speed
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/ElevenLabs/Models/Voice/Submodels/VoiceSettings.cs
    startLine: 37
  namespace: Glitch9.AIDevKit.ElevenLabs
  summary: >-
    Optional. Controls the speed of the generated speech.

    Values range from 0.7 to 1.2, with 1.0 being the default speed.

    Lower values create slower, more deliberate speech while higher values produce faster-paced speech.

    Extreme values can impact the quality of the generated speech.
  example: []
  syntax:
    content: public double? Speed { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property Speed As Double?
  overload: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Speed*
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseStyleExaggeration
  commentId: P:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseStyleExaggeration
  id: UseStyleExaggeration
  parent: Glitch9.AIDevKit.ElevenLabs.VoiceSettings
  langs:
  - csharp
  - vb
  name: UseStyleExaggeration
  nameWithType: VoiceSettings.UseStyleExaggeration
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseStyleExaggeration
  type: Property
  source:
    id: UseStyleExaggeration
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/ElevenLabs/Models/Voice/Submodels/VoiceSettings.cs
    startLine: 42
  namespace: Glitch9.AIDevKit.ElevenLabs
  summary: Optional. The use of style exaggeration in the voice output.
  example: []
  syntax:
    content: public bool? UseStyleExaggeration { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public Property UseStyleExaggeration As Boolean?
  overload: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseStyleExaggeration*
references:
- uid: Glitch9.AIDevKit.ElevenLabs
  commentId: N:Glitch9.AIDevKit.ElevenLabs
  href: Glitch9.html
  name: Glitch9.AIDevKit.ElevenLabs
  nameWithType: Glitch9.AIDevKit.ElevenLabs
  fullName: Glitch9.AIDevKit.ElevenLabs
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.ElevenLabs
    name: ElevenLabs
    href: Glitch9.AIDevKit.ElevenLabs.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.ElevenLabs
    name: ElevenLabs
    href: Glitch9.AIDevKit.ElevenLabs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Stability*
  commentId: Overload:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Stability
  href: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.html#Glitch9_AIDevKit_ElevenLabs_VoiceSettings_Stability
  name: Stability
  nameWithType: VoiceSettings.Stability
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Stability
- uid: System.Nullable{System.Double}
  commentId: T:System.Nullable{System.Double}
  parent: System
  definition: System.Nullable`1
  name: double?
  nameWithType: double?
  fullName: double?
  nameWithType.vb: Double?
  fullName.vb: Double?
  name.vb: Double?
  spec.csharp:
  - uid: System.Double
    name: double
    isExternal: true
  - name: '?'
  spec.vb:
  - uid: System.Double
    name: Double
    isExternal: true
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.SimilarityBoost*
  commentId: Overload:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.SimilarityBoost
  href: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.html#Glitch9_AIDevKit_ElevenLabs_VoiceSettings_SimilarityBoost
  name: SimilarityBoost
  nameWithType: VoiceSettings.SimilarityBoost
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.SimilarityBoost
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Style*
  commentId: Overload:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Style
  href: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.html#Glitch9_AIDevKit_ElevenLabs_VoiceSettings_Style
  name: Style
  nameWithType: VoiceSettings.Style
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Style
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseSpeakerBoost*
  commentId: Overload:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseSpeakerBoost
  href: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.html#Glitch9_AIDevKit_ElevenLabs_VoiceSettings_UseSpeakerBoost
  name: UseSpeakerBoost
  nameWithType: VoiceSettings.UseSpeakerBoost
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseSpeakerBoost
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: bool?
  nameWithType: bool?
  fullName: bool?
  nameWithType.vb: Boolean?
  fullName.vb: Boolean?
  name.vb: Boolean?
  spec.csharp:
  - uid: System.Boolean
    name: bool
    isExternal: true
  - name: '?'
  spec.vb:
  - uid: System.Boolean
    name: Boolean
    isExternal: true
  - name: '?'
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Speed*
  commentId: Overload:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Speed
  href: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.html#Glitch9_AIDevKit_ElevenLabs_VoiceSettings_Speed
  name: Speed
  nameWithType: VoiceSettings.Speed
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.Speed
- uid: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseStyleExaggeration*
  commentId: Overload:Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseStyleExaggeration
  href: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.html#Glitch9_AIDevKit_ElevenLabs_VoiceSettings_UseStyleExaggeration
  name: UseStyleExaggeration
  nameWithType: VoiceSettings.UseStyleExaggeration
  fullName: Glitch9.AIDevKit.ElevenLabs.VoiceSettings.UseStyleExaggeration
