### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory
  commentId: T:Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory
  id: MubertClientSettingsFactory
  parent: Glitch9.AIDevKit.Mubert
  children:
  - Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSerializerSettings
  - Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSettings
  langs:
  - csharp
  - vb
  name: MubertClientSettingsFactory
  nameWithType: MubertClientSettingsFactory
  fullName: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory
  type: Class
  source:
    id: MubertClientSettingsFactory
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Mubert/Client/Mubert.cs
    startLine: 7
  namespace: Glitch9.AIDevKit.Mubert
  syntax:
    content: 'public class MubertClientSettingsFactory : AIClientSettingsFactory'
    content.vb: Public Class MubertClientSettingsFactory Inherits AIClientSettingsFactory
  inheritance:
  - System.Object
  - Glitch9.AIDevKit.Client.AIClientSettingsFactory
  inheritedMembers:
  - Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
- uid: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSettings
  commentId: M:Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSettings
  id: CreateSettings
  parent: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory
  langs:
  - csharp
  - vb
  name: CreateSettings()
  nameWithType: MubertClientSettingsFactory.CreateSettings()
  fullName: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSettings()
  type: Method
  source:
    id: CreateSettings
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Mubert/Client/Mubert.cs
    startLine: 9
  namespace: Glitch9.AIDevKit.Mubert
  example: []
  syntax:
    content: protected override CRUDClientSettings CreateSettings()
    return:
      type: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
    content.vb: Protected Overrides Function CreateSettings() As CRUDClientSettings
  overridden: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  overload: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSettings*
- uid: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSerializerSettings
  commentId: M:Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSerializerSettings
  id: CreateSerializerSettings
  parent: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory
  langs:
  - csharp
  - vb
  name: CreateSerializerSettings()
  nameWithType: MubertClientSettingsFactory.CreateSerializerSettings()
  fullName: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSerializerSettings()
  type: Method
  source:
    id: CreateSerializerSettings
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Mubert/Client/Mubert.cs
    startLine: 21
  namespace: Glitch9.AIDevKit.Mubert
  example: []
  syntax:
    content: protected override AIClientSerializerSettings CreateSerializerSettings()
    return:
      type: Glitch9.AIDevKit.Client.AIClientSerializerSettings
    content.vb: Protected Overrides Function CreateSerializerSettings() As AIClientSerializerSettings
  overridden: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  overload: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSerializerSettings*
references:
- uid: Glitch9.AIDevKit.Mubert
  commentId: N:Glitch9.AIDevKit.Mubert
  href: Glitch9.html
  name: Glitch9.AIDevKit.Mubert
  nameWithType: Glitch9.AIDevKit.Mubert
  fullName: Glitch9.AIDevKit.Mubert
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Mubert
    name: Mubert
    href: Glitch9.AIDevKit.Mubert.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Mubert
    name: Mubert
    href: Glitch9.AIDevKit.Mubert.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  commentId: T:Glitch9.AIDevKit.Client.AIClientSettingsFactory
  parent: Glitch9.AIDevKit.Client
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html
  name: AIClientSettingsFactory
  nameWithType: AIClientSettingsFactory
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  name: Create()
  nameWithType: AIClientSettingsFactory.Create()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
    name: Create
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
    name: Create
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Client
  commentId: N:Glitch9.AIDevKit.Client
  href: Glitch9.html
  name: Glitch9.AIDevKit.Client
  nameWithType: Glitch9.AIDevKit.Client
  fullName: Glitch9.AIDevKit.Client
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  name: CreateSettings()
  nameWithType: AIClientSettingsFactory.CreateSettings()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
    name: CreateSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
    name: CreateSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  - name: (
  - name: )
- uid: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSettings*
  commentId: Overload:Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSettings
  href: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.html#Glitch9_AIDevKit_Mubert_MubertClientSettingsFactory_CreateSettings
  name: CreateSettings
  nameWithType: MubertClientSettingsFactory.CreateSettings
  fullName: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSettings
- uid: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
  commentId: T:Glitch9.IO.Networking.RESTApi.CRUDClientSettings
  parent: Glitch9.IO.Networking.RESTApi
  name: CRUDClientSettings
  nameWithType: CRUDClientSettings
  fullName: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
- uid: Glitch9.IO.Networking.RESTApi
  commentId: N:Glitch9.IO.Networking.RESTApi
  href: Glitch9.html
  name: Glitch9.IO.Networking.RESTApi
  nameWithType: Glitch9.IO.Networking.RESTApi
  fullName: Glitch9.IO.Networking.RESTApi
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.IO
    name: IO
    href: Glitch9.IO.html
  - name: .
  - uid: Glitch9.IO.Networking
    name: Networking
    href: Glitch9.IO.Networking.html
  - name: .
  - uid: Glitch9.IO.Networking.RESTApi
    name: RESTApi
    href: Glitch9.IO.Networking.RESTApi.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.IO
    name: IO
    href: Glitch9.IO.html
  - name: .
  - uid: Glitch9.IO.Networking
    name: Networking
    href: Glitch9.IO.Networking.html
  - name: .
  - uid: Glitch9.IO.Networking.RESTApi
    name: RESTApi
    href: Glitch9.IO.Networking.RESTApi.html
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  name: CreateSerializerSettings()
  nameWithType: AIClientSettingsFactory.CreateSerializerSettings()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
    name: CreateSerializerSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
    name: CreateSerializerSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  - name: (
  - name: )
- uid: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSerializerSettings*
  commentId: Overload:Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSerializerSettings
  href: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.html#Glitch9_AIDevKit_Mubert_MubertClientSettingsFactory_CreateSerializerSettings
  name: CreateSerializerSettings
  nameWithType: MubertClientSettingsFactory.CreateSerializerSettings
  fullName: Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory.CreateSerializerSettings
- uid: Glitch9.AIDevKit.Client.AIClientSerializerSettings
  commentId: T:Glitch9.AIDevKit.Client.AIClientSerializerSettings
  parent: Glitch9.AIDevKit.Client
  href: Glitch9.AIDevKit.Client.AIClientSerializerSettings.html
  name: AIClientSerializerSettings
  nameWithType: AIClientSerializerSettings
  fullName: Glitch9.AIDevKit.Client.AIClientSerializerSettings
