### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Google.VoiceConfig
  commentId: T:Glitch9.AIDevKit.Google.VoiceConfig
  id: VoiceConfig
  parent: Glitch9.AIDevKit.Google
  children:
  - Glitch9.AIDevKit.Google.VoiceConfig.PrebuiltVoiceConfig
  langs:
  - csharp
  - vb
  name: VoiceConfig
  nameWithType: VoiceConfig
  fullName: Glitch9.AIDevKit.Google.VoiceConfig
  type: Class
  source:
    id: VoiceConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/Components/GenerationConfig.cs
    startLine: 142
  namespace: Glitch9.AIDevKit.Google
  syntax:
    content: public class VoiceConfig
    content.vb: Public Class VoiceConfig
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.Google.VoiceConfig.PrebuiltVoiceConfig
  commentId: P:Glitch9.AIDevKit.Google.VoiceConfig.PrebuiltVoiceConfig
  id: PrebuiltVoiceConfig
  parent: Glitch9.AIDevKit.Google.VoiceConfig
  langs:
  - csharp
  - vb
  name: PrebuiltVoiceConfig
  nameWithType: VoiceConfig.PrebuiltVoiceConfig
  fullName: Glitch9.AIDevKit.Google.VoiceConfig.PrebuiltVoiceConfig
  type: Property
  source:
    id: PrebuiltVoiceConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/Components/GenerationConfig.cs
    startLine: 147
  namespace: Glitch9.AIDevKit.Google
  summary: Optional. The configuration for the prebuilt voice to use.
  example: []
  syntax:
    content: public PrebuiltVoiceConfig PrebuiltVoiceConfig { get; set; }
    parameters: []
    return:
      type: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig
    content.vb: Public Property PrebuiltVoiceConfig As PrebuiltVoiceConfig
  overload: Glitch9.AIDevKit.Google.VoiceConfig.PrebuiltVoiceConfig*
references:
- uid: Glitch9.AIDevKit.Google
  commentId: N:Glitch9.AIDevKit.Google
  href: Glitch9.html
  name: Glitch9.AIDevKit.Google
  nameWithType: Glitch9.AIDevKit.Google
  fullName: Glitch9.AIDevKit.Google
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Google.VoiceConfig.PrebuiltVoiceConfig*
  commentId: Overload:Glitch9.AIDevKit.Google.VoiceConfig.PrebuiltVoiceConfig
  href: Glitch9.AIDevKit.Google.VoiceConfig.html#Glitch9_AIDevKit_Google_VoiceConfig_PrebuiltVoiceConfig
  name: PrebuiltVoiceConfig
  nameWithType: VoiceConfig.PrebuiltVoiceConfig
  fullName: Glitch9.AIDevKit.Google.VoiceConfig.PrebuiltVoiceConfig
- uid: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig
  commentId: T:Glitch9.AIDevKit.Google.PrebuiltVoiceConfig
  parent: Glitch9.AIDevKit.Google
  href: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.html
  name: PrebuiltVoiceConfig
  nameWithType: PrebuiltVoiceConfig
  fullName: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig
