### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  commentId: T:Glitch9.AIDevKit.Client.AIClientSettingsFactory
  id: AIClientSettingsFactory
  parent: Glitch9.AIDevKit.Client
  children:
  - Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  - Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  - Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  langs:
  - csharp
  - vb
  name: AIClientSettingsFactory
  nameWithType: AIClientSettingsFactory
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  type: Class
  source:
    id: AIClientSettingsFactory
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClient.cs
    startLine: 14
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: public abstract class AIClientSettingsFactory
    content.vb: Public MustInherit Class AIClientSettingsFactory
  inheritance:
  - System.Object
  derivedClasses:
  - Glitch9.AIDevKit.ElevenLabs.ElevenLabsClientSettingsFactory
  - Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory
  - Glitch9.AIDevKit.Mubert.MubertClientSettingsFactory
  - Glitch9.AIDevKit.Ollama.OllamaClientSettingsFactory
  - Glitch9.AIDevKit.OpenAI.OpenAIClientSettingsFactory
  - Glitch9.AIDevKit.OpenRouter.OpenRouterClientSettingsFactory
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  id: CreateSettings
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  langs:
  - csharp
  - vb
  name: CreateSettings()
  nameWithType: AIClientSettingsFactory.CreateSettings()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings()
  type: Method
  source:
    id: CreateSettings
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClient.cs
    startLine: 16
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: protected abstract CRUDClientSettings CreateSettings()
    return:
      type: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
    content.vb: Protected MustOverride Function CreateSettings() As CRUDClientSettings
  overload: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings*
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  id: CreateSerializerSettings
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  langs:
  - csharp
  - vb
  name: CreateSerializerSettings()
  nameWithType: AIClientSettingsFactory.CreateSerializerSettings()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings()
  type: Method
  source:
    id: CreateSerializerSettings
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClient.cs
    startLine: 17
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: protected abstract AIClientSerializerSettings CreateSerializerSettings()
    return:
      type: Glitch9.AIDevKit.Client.AIClientSerializerSettings
    content.vb: Protected MustOverride Function CreateSerializerSettings() As AIClientSerializerSettings
  overload: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings*
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  id: Create
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  langs:
  - csharp
  - vb
  name: Create()
  nameWithType: AIClientSettingsFactory.Create()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create()
  type: Method
  source:
    id: Create
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClient.cs
    startLine: 19
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: public CRUDClientSettings Create()
    return:
      type: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
    content.vb: Public Function Create() As CRUDClientSettings
  overload: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create*
references:
- uid: Glitch9.AIDevKit.Client
  commentId: N:Glitch9.AIDevKit.Client
  href: Glitch9.html
  name: Glitch9.AIDevKit.Client
  nameWithType: Glitch9.AIDevKit.Client
  fullName: Glitch9.AIDevKit.Client
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings*
  commentId: Overload:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  name: CreateSettings
  nameWithType: AIClientSettingsFactory.CreateSettings
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
- uid: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
  commentId: T:Glitch9.IO.Networking.RESTApi.CRUDClientSettings
  parent: Glitch9.IO.Networking.RESTApi
  name: CRUDClientSettings
  nameWithType: CRUDClientSettings
  fullName: Glitch9.IO.Networking.RESTApi.CRUDClientSettings
- uid: Glitch9.IO.Networking.RESTApi
  commentId: N:Glitch9.IO.Networking.RESTApi
  href: Glitch9.html
  name: Glitch9.IO.Networking.RESTApi
  nameWithType: Glitch9.IO.Networking.RESTApi
  fullName: Glitch9.IO.Networking.RESTApi
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.IO
    name: IO
    href: Glitch9.IO.html
  - name: .
  - uid: Glitch9.IO.Networking
    name: Networking
    href: Glitch9.IO.Networking.html
  - name: .
  - uid: Glitch9.IO.Networking.RESTApi
    name: RESTApi
    href: Glitch9.IO.Networking.RESTApi.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.IO
    name: IO
    href: Glitch9.IO.html
  - name: .
  - uid: Glitch9.IO.Networking
    name: Networking
    href: Glitch9.IO.Networking.html
  - name: .
  - uid: Glitch9.IO.Networking.RESTApi
    name: RESTApi
    href: Glitch9.IO.Networking.RESTApi.html
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings*
  commentId: Overload:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  name: CreateSerializerSettings
  nameWithType: AIClientSettingsFactory.CreateSerializerSettings
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
- uid: Glitch9.AIDevKit.Client.AIClientSerializerSettings
  commentId: T:Glitch9.AIDevKit.Client.AIClientSerializerSettings
  parent: Glitch9.AIDevKit.Client
  href: Glitch9.AIDevKit.Client.AIClientSerializerSettings.html
  name: AIClientSerializerSettings
  nameWithType: AIClientSerializerSettings
  fullName: Glitch9.AIDevKit.Client.AIClientSerializerSettings
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create*
  commentId: Overload:Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  name: Create
  nameWithType: AIClientSettingsFactory.Create
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
