### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Ollama.OllamaSettings
  commentId: T:Glitch9.AIDevKit.Ollama.OllamaSettings
  id: OllamaSettings
  parent: Glitch9.AIDevKit.Ollama
  children:
  - Glitch9.AIDevKit.Ollama.OllamaSettings.CheckConnectionAsync
  - Glitch9.AIDevKit.Ollama.OllamaSettings.DefaultModel
  - Glitch9.AIDevKit.Ollama.OllamaSettings.GetEndpoint
  - Glitch9.AIDevKit.Ollama.OllamaSettings.IsDefaultModel(System.String,Glitch9.AIDevKit.ModelFeature)
  langs:
  - csharp
  - vb
  name: OllamaSettings
  nameWithType: OllamaSettings
  fullName: Glitch9.AIDevKit.Ollama.OllamaSettings
  type: Class
  source:
    id: OllamaSettings
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/OllamaSettings.cs
    startLine: 7
  namespace: Glitch9.AIDevKit.Ollama
  syntax:
    content: 'public class OllamaSettings : ScriptableResource<OllamaSettings>'
    content.vb: Public Class OllamaSettings Inherits ScriptableResource(Of OllamaSettings)
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.Ollama.OllamaSettings.DefaultModel
  commentId: P:Glitch9.AIDevKit.Ollama.OllamaSettings.DefaultModel
  id: DefaultModel
  parent: Glitch9.AIDevKit.Ollama.OllamaSettings
  langs:
  - csharp
  - vb
  name: DefaultModel
  nameWithType: OllamaSettings.DefaultModel
  fullName: Glitch9.AIDevKit.Ollama.OllamaSettings.DefaultModel
  type: Property
  source:
    id: DefaultModel
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/OllamaSettings.cs
    startLine: 17
  namespace: Glitch9.AIDevKit.Ollama
  syntax:
    content: public static string DefaultModel { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property DefaultModel As String
  overload: Glitch9.AIDevKit.Ollama.OllamaSettings.DefaultModel*
- uid: Glitch9.AIDevKit.Ollama.OllamaSettings.GetEndpoint
  commentId: M:Glitch9.AIDevKit.Ollama.OllamaSettings.GetEndpoint
  id: GetEndpoint
  parent: Glitch9.AIDevKit.Ollama.OllamaSettings
  langs:
  - csharp
  - vb
  name: GetEndpoint()
  nameWithType: OllamaSettings.GetEndpoint()
  fullName: Glitch9.AIDevKit.Ollama.OllamaSettings.GetEndpoint()
  type: Method
  source:
    id: GetEndpoint
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/OllamaSettings.cs
    startLine: 19
  namespace: Glitch9.AIDevKit.Ollama
  syntax:
    content: public static string GetEndpoint()
    return:
      type: System.String
    content.vb: Public Shared Function GetEndpoint() As String
  overload: Glitch9.AIDevKit.Ollama.OllamaSettings.GetEndpoint*
- uid: Glitch9.AIDevKit.Ollama.OllamaSettings.CheckConnectionAsync
  commentId: M:Glitch9.AIDevKit.Ollama.OllamaSettings.CheckConnectionAsync
  id: CheckConnectionAsync
  parent: Glitch9.AIDevKit.Ollama.OllamaSettings
  langs:
  - csharp
  - vb
  name: CheckConnectionAsync()
  nameWithType: OllamaSettings.CheckConnectionAsync()
  fullName: Glitch9.AIDevKit.Ollama.OllamaSettings.CheckConnectionAsync()
  type: Method
  source:
    id: CheckConnectionAsync
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/OllamaSettings.cs
    startLine: 29
  namespace: Glitch9.AIDevKit.Ollama
  syntax:
    content: public static UniTask<bool> CheckConnectionAsync()
    return:
      type: UniTask{System.Boolean}
    content.vb: Public Shared Function CheckConnectionAsync() As UniTask(Of Boolean)
  overload: Glitch9.AIDevKit.Ollama.OllamaSettings.CheckConnectionAsync*
- uid: Glitch9.AIDevKit.Ollama.OllamaSettings.IsDefaultModel(System.String,Glitch9.AIDevKit.ModelFeature)
  commentId: M:Glitch9.AIDevKit.Ollama.OllamaSettings.IsDefaultModel(System.String,Glitch9.AIDevKit.ModelFeature)
  id: IsDefaultModel(System.String,Glitch9.AIDevKit.ModelFeature)
  parent: Glitch9.AIDevKit.Ollama.OllamaSettings
  langs:
  - csharp
  - vb
  name: IsDefaultModel(string, ModelFeature)
  nameWithType: OllamaSettings.IsDefaultModel(string, ModelFeature)
  fullName: Glitch9.AIDevKit.Ollama.OllamaSettings.IsDefaultModel(string, Glitch9.AIDevKit.ModelFeature)
  type: Method
  source:
    id: IsDefaultModel
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/OllamaSettings.cs
    startLine: 36
  namespace: Glitch9.AIDevKit.Ollama
  syntax:
    content: public static bool IsDefaultModel(string id, ModelFeature cap)
    parameters:
    - id: id
      type: System.String
    - id: cap
      type: Glitch9.AIDevKit.ModelFeature
    return:
      type: System.Boolean
    content.vb: Public Shared Function IsDefaultModel(id As String, cap As ModelFeature) As Boolean
  overload: Glitch9.AIDevKit.Ollama.OllamaSettings.IsDefaultModel*
  nameWithType.vb: OllamaSettings.IsDefaultModel(String, ModelFeature)
  fullName.vb: Glitch9.AIDevKit.Ollama.OllamaSettings.IsDefaultModel(String, Glitch9.AIDevKit.ModelFeature)
  name.vb: IsDefaultModel(String, ModelFeature)
references:
- uid: Glitch9.AIDevKit.Ollama
  commentId: N:Glitch9.AIDevKit.Ollama
  href: Glitch9.html
  name: Glitch9.AIDevKit.Ollama
  nameWithType: Glitch9.AIDevKit.Ollama
  fullName: Glitch9.AIDevKit.Ollama
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Ollama
    name: Ollama
    href: Glitch9.AIDevKit.Ollama.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Ollama
    name: Ollama
    href: Glitch9.AIDevKit.Ollama.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Ollama.OllamaSettings.DefaultModel*
  commentId: Overload:Glitch9.AIDevKit.Ollama.OllamaSettings.DefaultModel
  href: Glitch9.AIDevKit.Ollama.OllamaSettings.html#Glitch9_AIDevKit_Ollama_OllamaSettings_DefaultModel
  name: DefaultModel
  nameWithType: OllamaSettings.DefaultModel
  fullName: Glitch9.AIDevKit.Ollama.OllamaSettings.DefaultModel
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Glitch9.AIDevKit.Ollama.OllamaSettings.GetEndpoint*
  commentId: Overload:Glitch9.AIDevKit.Ollama.OllamaSettings.GetEndpoint
  href: Glitch9.AIDevKit.Ollama.OllamaSettings.html#Glitch9_AIDevKit_Ollama_OllamaSettings_GetEndpoint
  name: GetEndpoint
  nameWithType: OllamaSettings.GetEndpoint
  fullName: Glitch9.AIDevKit.Ollama.OllamaSettings.GetEndpoint
- uid: Glitch9.AIDevKit.Ollama.OllamaSettings.CheckConnectionAsync*
  commentId: Overload:Glitch9.AIDevKit.Ollama.OllamaSettings.CheckConnectionAsync
  href: Glitch9.AIDevKit.Ollama.OllamaSettings.html#Glitch9_AIDevKit_Ollama_OllamaSettings_CheckConnectionAsync
  name: CheckConnectionAsync
  nameWithType: OllamaSettings.CheckConnectionAsync
  fullName: Glitch9.AIDevKit.Ollama.OllamaSettings.CheckConnectionAsync
- uid: UniTask{System.Boolean}
  commentId: '!:UniTask{System.Boolean}'
  definition: UniTask`1
  name: UniTask<bool>
  nameWithType: UniTask<bool>
  fullName: UniTask<bool>
  nameWithType.vb: UniTask(Of Boolean)
  fullName.vb: UniTask(Of Boolean)
  name.vb: UniTask(Of Boolean)
  spec.csharp:
  - uid: UniTask`1
    name: UniTask
    isExternal: true
  - name: <
  - uid: System.Boolean
    name: bool
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: UniTask`1
    name: UniTask
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
  - name: )
- uid: UniTask`1
  isExternal: true
  name: UniTask<>
  nameWithType: UniTask<>
  fullName: UniTask<>
  nameWithType.vb: UniTask(Of )
  fullName.vb: UniTask(Of )
  name.vb: UniTask(Of )
  spec.csharp:
  - uid: UniTask`1
    name: UniTask
    isExternal: true
  - name: <
  - name: ''
  - name: '>'
  spec.vb:
  - uid: UniTask`1
    name: UniTask
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: ''
  - name: )
- uid: Glitch9.AIDevKit.Ollama.OllamaSettings.IsDefaultModel*
  commentId: Overload:Glitch9.AIDevKit.Ollama.OllamaSettings.IsDefaultModel
  href: Glitch9.AIDevKit.Ollama.OllamaSettings.html#Glitch9_AIDevKit_Ollama_OllamaSettings_IsDefaultModel_System_String_Glitch9_AIDevKit_ModelFeature_
  name: IsDefaultModel
  nameWithType: OllamaSettings.IsDefaultModel
  fullName: Glitch9.AIDevKit.Ollama.OllamaSettings.IsDefaultModel
- uid: Glitch9.AIDevKit.ModelFeature
  commentId: T:Glitch9.AIDevKit.ModelFeature
  parent: Glitch9.AIDevKit
  href: Glitch9.AIDevKit.ModelFeature.html
  name: ModelFeature
  nameWithType: ModelFeature
  fullName: Glitch9.AIDevKit.ModelFeature
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Glitch9.AIDevKit
  commentId: N:Glitch9.AIDevKit
  href: Glitch9.html
  name: Glitch9.AIDevKit
  nameWithType: Glitch9.AIDevKit
  fullName: Glitch9.AIDevKit
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
