### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Google.SpeechConfig
  commentId: T:Glitch9.AIDevKit.Google.SpeechConfig
  id: SpeechConfig
  parent: Glitch9.AIDevKit.Google
  children:
  - Glitch9.AIDevKit.Google.SpeechConfig.VoiceConfig
  langs:
  - csharp
  - vb
  name: SpeechConfig
  nameWithType: SpeechConfig
  fullName: Glitch9.AIDevKit.Google.SpeechConfig
  type: Class
  source:
    id: SpeechConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/Components/GenerationConfig.cs
    startLine: 134
  namespace: Glitch9.AIDevKit.Google
  syntax:
    content: public class SpeechConfig
    content.vb: Public Class SpeechConfig
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.Google.SpeechConfig.VoiceConfig
  commentId: P:Glitch9.AIDevKit.Google.SpeechConfig.VoiceConfig
  id: VoiceConfig
  parent: Glitch9.AIDevKit.Google.SpeechConfig
  langs:
  - csharp
  - vb
  name: VoiceConfig
  nameWithType: SpeechConfig.VoiceConfig
  fullName: Glitch9.AIDevKit.Google.SpeechConfig.VoiceConfig
  type: Property
  source:
    id: VoiceConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/Components/GenerationConfig.cs
    startLine: 139
  namespace: Glitch9.AIDevKit.Google
  summary: Optional. The configuration for the speaker to use.
  example: []
  syntax:
    content: public VoiceConfig VoiceConfig { get; set; }
    parameters: []
    return:
      type: Glitch9.AIDevKit.Google.VoiceConfig
    content.vb: Public Property VoiceConfig As VoiceConfig
  overload: Glitch9.AIDevKit.Google.SpeechConfig.VoiceConfig*
references:
- uid: Glitch9.AIDevKit.Google
  commentId: N:Glitch9.AIDevKit.Google
  href: Glitch9.html
  name: Glitch9.AIDevKit.Google
  nameWithType: Glitch9.AIDevKit.Google
  fullName: Glitch9.AIDevKit.Google
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Google.SpeechConfig.VoiceConfig*
  commentId: Overload:Glitch9.AIDevKit.Google.SpeechConfig.VoiceConfig
  href: Glitch9.AIDevKit.Google.SpeechConfig.html#Glitch9_AIDevKit_Google_SpeechConfig_VoiceConfig
  name: VoiceConfig
  nameWithType: SpeechConfig.VoiceConfig
  fullName: Glitch9.AIDevKit.Google.SpeechConfig.VoiceConfig
- uid: Glitch9.AIDevKit.Google.VoiceConfig
  commentId: T:Glitch9.AIDevKit.Google.VoiceConfig
  parent: Glitch9.AIDevKit.Google
  href: Glitch9.AIDevKit.Google.VoiceConfig.html
  name: VoiceConfig
  nameWithType: VoiceConfig
  fullName: Glitch9.AIDevKit.Google.VoiceConfig
