### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory
  commentId: T:Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory
  id: GenerativeAIClientSettingsFactory
  parent: Glitch9.AIDevKit.Google
  children:
  - Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSerializerSettings
  - Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSettings
  langs:
  - csharp
  - vb
  name: GenerativeAIClientSettingsFactory
  nameWithType: GenerativeAIClientSettingsFactory
  fullName: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory
  type: Class
  source:
    id: GenerativeAIClientSettingsFactory
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Client/GenerativeAI.cs
    startLine: 10
  namespace: Glitch9.AIDevKit.Google
  syntax:
    content: 'public class GenerativeAIClientSettingsFactory : AIClientSettingsFactory'
    content.vb: Public Class GenerativeAIClientSettingsFactory Inherits AIClientSettingsFactory
  inheritance:
  - System.Object
  - Glitch9.AIDevKit.Client.AIClientSettingsFactory
  inheritedMembers:
  - Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
- uid: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSettings
  commentId: M:Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSettings
  id: CreateSettings
  parent: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory
  langs:
  - csharp
  - vb
  name: CreateSettings()
  nameWithType: GenerativeAIClientSettingsFactory.CreateSettings()
  fullName: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSettings()
  type: Method
  source:
    id: CreateSettings
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Client/GenerativeAI.cs
    startLine: 12
  namespace: Glitch9.AIDevKit.Google
  example: []
  syntax:
    content: protected override CRUDClientSettings CreateSettings()
    return:
      type: CRUDClientSettings
    content.vb: Protected Overrides Function CreateSettings() As CRUDClientSettings
  overridden: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  overload: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSettings*
- uid: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSerializerSettings
  commentId: M:Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSerializerSettings
  id: CreateSerializerSettings
  parent: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory
  langs:
  - csharp
  - vb
  name: CreateSerializerSettings()
  nameWithType: GenerativeAIClientSettingsFactory.CreateSerializerSettings()
  fullName: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSerializerSettings()
  type: Method
  source:
    id: CreateSerializerSettings
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Client/GenerativeAI.cs
    startLine: 24
  namespace: Glitch9.AIDevKit.Google
  example: []
  syntax:
    content: protected override AIClientSerializerSettings CreateSerializerSettings()
    return:
      type: Glitch9.AIDevKit.Client.AIClientSerializerSettings
    content.vb: Protected Overrides Function CreateSerializerSettings() As AIClientSerializerSettings
  overridden: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  overload: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSerializerSettings*
references:
- uid: Glitch9.AIDevKit.Google
  commentId: N:Glitch9.AIDevKit.Google
  href: Glitch9.html
  name: Glitch9.AIDevKit.Google
  nameWithType: Glitch9.AIDevKit.Google
  fullName: Glitch9.AIDevKit.Google
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  commentId: T:Glitch9.AIDevKit.Client.AIClientSettingsFactory
  parent: Glitch9.AIDevKit.Client
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html
  name: AIClientSettingsFactory
  nameWithType: AIClientSettingsFactory
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  name: Create()
  nameWithType: AIClientSettingsFactory.Create()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
    name: Create
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.Create
    name: Create
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_Create
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Client
  commentId: N:Glitch9.AIDevKit.Client
  href: Glitch9.html
  name: Glitch9.AIDevKit.Client
  nameWithType: Glitch9.AIDevKit.Client
  fullName: Glitch9.AIDevKit.Client
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  name: CreateSettings()
  nameWithType: AIClientSettingsFactory.CreateSettings()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
    name: CreateSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSettings
    name: CreateSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSettings
  - name: (
  - name: )
- uid: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSettings*
  commentId: Overload:Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSettings
  href: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.html#Glitch9_AIDevKit_Google_GenerativeAIClientSettingsFactory_CreateSettings
  name: CreateSettings
  nameWithType: GenerativeAIClientSettingsFactory.CreateSettings
  fullName: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSettings
- uid: CRUDClientSettings
  isExternal: true
  name: CRUDClientSettings
  nameWithType: CRUDClientSettings
  fullName: CRUDClientSettings
- uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
  parent: Glitch9.AIDevKit.Client.AIClientSettingsFactory
  href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  name: CreateSerializerSettings()
  nameWithType: AIClientSettingsFactory.CreateSerializerSettings()
  fullName: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
    name: CreateSerializerSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettingsFactory.CreateSerializerSettings
    name: CreateSerializerSettings
    href: Glitch9.AIDevKit.Client.AIClientSettingsFactory.html#Glitch9_AIDevKit_Client_AIClientSettingsFactory_CreateSerializerSettings
  - name: (
  - name: )
- uid: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSerializerSettings*
  commentId: Overload:Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSerializerSettings
  href: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.html#Glitch9_AIDevKit_Google_GenerativeAIClientSettingsFactory_CreateSerializerSettings
  name: CreateSerializerSettings
  nameWithType: GenerativeAIClientSettingsFactory.CreateSerializerSettings
  fullName: Glitch9.AIDevKit.Google.GenerativeAIClientSettingsFactory.CreateSerializerSettings
- uid: Glitch9.AIDevKit.Client.AIClientSerializerSettings
  commentId: T:Glitch9.AIDevKit.Client.AIClientSerializerSettings
  parent: Glitch9.AIDevKit.Client
  href: Glitch9.AIDevKit.Client.AIClientSerializerSettings.html
  name: AIClientSerializerSettings
  nameWithType: AIClientSerializerSettings
  fullName: Glitch9.AIDevKit.Client.AIClientSerializerSettings
