### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig
  commentId: T:Glitch9.AIDevKit.Google.PrebuiltVoiceConfig
  id: PrebuiltVoiceConfig
  parent: Glitch9.AIDevKit.Google
  children:
  - Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.VoiceName
  langs:
  - csharp
  - vb
  name: PrebuiltVoiceConfig
  nameWithType: PrebuiltVoiceConfig
  fullName: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig
  type: Class
  source:
    id: PrebuiltVoiceConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/Components/GenerationConfig.cs
    startLine: 150
  namespace: Glitch9.AIDevKit.Google
  syntax:
    content: public class PrebuiltVoiceConfig
    content.vb: Public Class PrebuiltVoiceConfig
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.VoiceName
  commentId: P:Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.VoiceName
  id: VoiceName
  parent: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig
  langs:
  - csharp
  - vb
  name: VoiceName
  nameWithType: PrebuiltVoiceConfig.VoiceName
  fullName: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.VoiceName
  type: Property
  source:
    id: VoiceName
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/Components/GenerationConfig.cs
    startLine: 155
  namespace: Glitch9.AIDevKit.Google
  summary: Optional. The name of the preset voice to use.
  example: []
  syntax:
    content: public string VoiceName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property VoiceName As String
  overload: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.VoiceName*
references:
- uid: Glitch9.AIDevKit.Google
  commentId: N:Glitch9.AIDevKit.Google
  href: Glitch9.html
  name: Glitch9.AIDevKit.Google
  nameWithType: Glitch9.AIDevKit.Google
  fullName: Glitch9.AIDevKit.Google
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.VoiceName*
  commentId: Overload:Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.VoiceName
  href: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.html#Glitch9_AIDevKit_Google_PrebuiltVoiceConfig_VoiceName
  name: VoiceName
  nameWithType: PrebuiltVoiceConfig.VoiceName
  fullName: Glitch9.AIDevKit.Google.PrebuiltVoiceConfig.VoiceName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
