### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Client.AIClientSerializerSettings
  commentId: T:Glitch9.AIDevKit.Client.AIClientSerializerSettings
  id: AIClientSerializerSettings
  parent: Glitch9.AIDevKit.Client
  children:
  - Glitch9.AIDevKit.Client.AIClientSerializerSettings.Converters
  - Glitch9.AIDevKit.Client.AIClientSerializerSettings.TextCase
  langs:
  - csharp
  - vb
  name: AIClientSerializerSettings
  nameWithType: AIClientSerializerSettings
  fullName: Glitch9.AIDevKit.Client.AIClientSerializerSettings
  type: Class
  source:
    id: AIClientSerializerSettings
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClient.cs
    startLine: 8
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: public class AIClientSerializerSettings
    content.vb: Public Class AIClientSerializerSettings
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.Client.AIClientSerializerSettings.TextCase
  commentId: P:Glitch9.AIDevKit.Client.AIClientSerializerSettings.TextCase
  id: TextCase
  parent: Glitch9.AIDevKit.Client.AIClientSerializerSettings
  langs:
  - csharp
  - vb
  name: TextCase
  nameWithType: AIClientSerializerSettings.TextCase
  fullName: Glitch9.AIDevKit.Client.AIClientSerializerSettings.TextCase
  type: Property
  source:
    id: TextCase
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClient.cs
    startLine: 10
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: public TextCase TextCase { get; set; }
    parameters: []
    return:
      type: Glitch9.TextCase
    content.vb: Public Property TextCase As TextCase
  overload: Glitch9.AIDevKit.Client.AIClientSerializerSettings.TextCase*
- uid: Glitch9.AIDevKit.Client.AIClientSerializerSettings.Converters
  commentId: P:Glitch9.AIDevKit.Client.AIClientSerializerSettings.Converters
  id: Converters
  parent: Glitch9.AIDevKit.Client.AIClientSerializerSettings
  langs:
  - csharp
  - vb
  name: Converters
  nameWithType: AIClientSerializerSettings.Converters
  fullName: Glitch9.AIDevKit.Client.AIClientSerializerSettings.Converters
  type: Property
  source:
    id: Converters
    path: E:/UnityProjects/Glitch9/AI Development Kit Clean/AI Development Kit Clean/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Client/Core/AIClient.cs
    startLine: 11
  namespace: Glitch9.AIDevKit.Client
  syntax:
    content: public List<JsonConverter> Converters { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{JsonConverter}
    content.vb: Public Property Converters As List(Of JsonConverter)
  overload: Glitch9.AIDevKit.Client.AIClientSerializerSettings.Converters*
references:
- uid: Glitch9.AIDevKit.Client
  commentId: N:Glitch9.AIDevKit.Client
  href: Glitch9.html
  name: Glitch9.AIDevKit.Client
  nameWithType: Glitch9.AIDevKit.Client
  fullName: Glitch9.AIDevKit.Client
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Client.AIClientSerializerSettings.TextCase*
  commentId: Overload:Glitch9.AIDevKit.Client.AIClientSerializerSettings.TextCase
  href: Glitch9.AIDevKit.Client.AIClientSerializerSettings.html#Glitch9_AIDevKit_Client_AIClientSerializerSettings_TextCase
  name: TextCase
  nameWithType: AIClientSerializerSettings.TextCase
  fullName: Glitch9.AIDevKit.Client.AIClientSerializerSettings.TextCase
- uid: Glitch9.TextCase
  commentId: T:Glitch9.TextCase
  parent: Glitch9
  name: TextCase
  nameWithType: TextCase
  fullName: Glitch9.TextCase
- uid: Glitch9
  commentId: N:Glitch9
  href: Glitch9.html
  name: Glitch9
  nameWithType: Glitch9
  fullName: Glitch9
- uid: Glitch9.AIDevKit.Client.AIClientSerializerSettings.Converters*
  commentId: Overload:Glitch9.AIDevKit.Client.AIClientSerializerSettings.Converters
  href: Glitch9.AIDevKit.Client.AIClientSerializerSettings.html#Glitch9_AIDevKit_Client_AIClientSerializerSettings_Converters
  name: Converters
  nameWithType: AIClientSerializerSettings.Converters
  fullName: Glitch9.AIDevKit.Client.AIClientSerializerSettings.Converters
- uid: System.Collections.Generic.List{JsonConverter}
  commentId: T:System.Collections.Generic.List{JsonConverter}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<JsonConverter>
  nameWithType: List<JsonConverter>
  fullName: System.Collections.Generic.List<JsonConverter>
  nameWithType.vb: List(Of JsonConverter)
  fullName.vb: System.Collections.Generic.List(Of JsonConverter)
  name.vb: List(Of JsonConverter)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - uid: JsonConverter
    name: JsonConverter
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: JsonConverter
    name: JsonConverter
    isExternal: true
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
