### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Google.GenerateMediaConfig
  commentId: T:Glitch9.AIDevKit.Google.GenerateMediaConfig
  id: GenerateMediaConfig
  parent: Glitch9.AIDevKit.Google
  children:
  - Glitch9.AIDevKit.Google.GenerateMediaConfig.AspectRatio
  - Glitch9.AIDevKit.Google.GenerateMediaConfig.NumberOfImages
  - Glitch9.AIDevKit.Google.GenerateMediaConfig.PersonGeneration
  langs:
  - csharp
  - vb
  name: GenerateMediaConfig
  nameWithType: GenerateMediaConfig
  fullName: Glitch9.AIDevKit.Google.GenerateMediaConfig
  type: Class
  source:
    id: GenerateMediaConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateMedia/GenerateMediaRequest.cs
    startLine: 54
  namespace: Glitch9.AIDevKit.Google
  syntax:
    content: public class GenerateMediaConfig
    content.vb: Public Class GenerateMediaConfig
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.Google.GenerateMediaConfig.NumberOfImages
  commentId: P:Glitch9.AIDevKit.Google.GenerateMediaConfig.NumberOfImages
  id: NumberOfImages
  parent: Glitch9.AIDevKit.Google.GenerateMediaConfig
  langs:
  - csharp
  - vb
  name: NumberOfImages
  nameWithType: GenerateMediaConfig.NumberOfImages
  fullName: Glitch9.AIDevKit.Google.GenerateMediaConfig.NumberOfImages
  type: Property
  source:
    id: NumberOfImages
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateMedia/GenerateMediaRequest.cs
    startLine: 60
  namespace: Glitch9.AIDevKit.Google
  syntax:
    content: public int NumberOfImages { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property NumberOfImages As Integer
  overload: Glitch9.AIDevKit.Google.GenerateMediaConfig.NumberOfImages*
- uid: Glitch9.AIDevKit.Google.GenerateMediaConfig.AspectRatio
  commentId: P:Glitch9.AIDevKit.Google.GenerateMediaConfig.AspectRatio
  id: AspectRatio
  parent: Glitch9.AIDevKit.Google.GenerateMediaConfig
  langs:
  - csharp
  - vb
  name: AspectRatio
  nameWithType: GenerateMediaConfig.AspectRatio
  fullName: Glitch9.AIDevKit.Google.GenerateMediaConfig.AspectRatio
  type: Property
  source:
    id: AspectRatio
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateMedia/GenerateMediaRequest.cs
    startLine: 66
  namespace: Glitch9.AIDevKit.Google
  summary: >-
    Changes the aspect ratio of the generated image. 

    Supported values are "1:1", "3:4", "4:3", "9:16", and "16:9". The default is "1:1".
  example: []
  syntax:
    content: public AspectRatio AspectRatio { get; set; }
    parameters: []
    return:
      type: Glitch9.AIDevKit.Google.AspectRatio
    content.vb: Public Property AspectRatio As AspectRatio
  overload: Glitch9.AIDevKit.Google.GenerateMediaConfig.AspectRatio*
- uid: Glitch9.AIDevKit.Google.GenerateMediaConfig.PersonGeneration
  commentId: P:Glitch9.AIDevKit.Google.GenerateMediaConfig.PersonGeneration
  id: PersonGeneration
  parent: Glitch9.AIDevKit.Google.GenerateMediaConfig
  langs:
  - csharp
  - vb
  name: PersonGeneration
  nameWithType: GenerateMediaConfig.PersonGeneration
  fullName: Glitch9.AIDevKit.Google.GenerateMediaConfig.PersonGeneration
  type: Property
  source:
    id: PersonGeneration
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateMedia/GenerateMediaRequest.cs
    startLine: 71
  namespace: Glitch9.AIDevKit.Google
  summary: Allow the model to generate images of people.
  example: []
  syntax:
    content: public PersonGeneration PersonGeneration { get; set; }
    parameters: []
    return:
      type: Glitch9.AIDevKit.Google.PersonGeneration
    content.vb: Public Property PersonGeneration As PersonGeneration
  overload: Glitch9.AIDevKit.Google.GenerateMediaConfig.PersonGeneration*
references:
- uid: Glitch9.AIDevKit.Google
  commentId: N:Glitch9.AIDevKit.Google
  href: Glitch9.html
  name: Glitch9.AIDevKit.Google
  nameWithType: Glitch9.AIDevKit.Google
  fullName: Glitch9.AIDevKit.Google
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Google.GenerateMediaConfig.NumberOfImages*
  commentId: Overload:Glitch9.AIDevKit.Google.GenerateMediaConfig.NumberOfImages
  href: Glitch9.AIDevKit.Google.GenerateMediaConfig.html#Glitch9_AIDevKit_Google_GenerateMediaConfig_NumberOfImages
  name: NumberOfImages
  nameWithType: GenerateMediaConfig.NumberOfImages
  fullName: Glitch9.AIDevKit.Google.GenerateMediaConfig.NumberOfImages
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Glitch9.AIDevKit.Google.GenerateMediaConfig.AspectRatio*
  commentId: Overload:Glitch9.AIDevKit.Google.GenerateMediaConfig.AspectRatio
  href: Glitch9.AIDevKit.Google.GenerateMediaConfig.html#Glitch9_AIDevKit_Google_GenerateMediaConfig_AspectRatio
  name: AspectRatio
  nameWithType: GenerateMediaConfig.AspectRatio
  fullName: Glitch9.AIDevKit.Google.GenerateMediaConfig.AspectRatio
- uid: Glitch9.AIDevKit.Google.AspectRatio
  commentId: T:Glitch9.AIDevKit.Google.AspectRatio
  parent: Glitch9.AIDevKit.Google
  href: Glitch9.AIDevKit.Google.AspectRatio.html
  name: AspectRatio
  nameWithType: AspectRatio
  fullName: Glitch9.AIDevKit.Google.AspectRatio
- uid: Glitch9.AIDevKit.Google.GenerateMediaConfig.PersonGeneration*
  commentId: Overload:Glitch9.AIDevKit.Google.GenerateMediaConfig.PersonGeneration
  href: Glitch9.AIDevKit.Google.GenerateMediaConfig.html#Glitch9_AIDevKit_Google_GenerateMediaConfig_PersonGeneration
  name: PersonGeneration
  nameWithType: GenerateMediaConfig.PersonGeneration
  fullName: Glitch9.AIDevKit.Google.GenerateMediaConfig.PersonGeneration
- uid: Glitch9.AIDevKit.Google.PersonGeneration
  commentId: T:Glitch9.AIDevKit.Google.PersonGeneration
  parent: Glitch9.AIDevKit.Google
  href: Glitch9.AIDevKit.Google.PersonGeneration.html
  name: PersonGeneration
  nameWithType: PersonGeneration
  fullName: Glitch9.AIDevKit.Google.PersonGeneration
