### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig
  commentId: T:Glitch9.AIDevKit.Google.SemanticRetrieverConfig
  id: SemanticRetrieverConfig
  parent: Glitch9.AIDevKit.Google
  children:
  - Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MaxChunksCount
  - Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MetadataFilters
  - Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MinimumRelevanceScore
  - Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Query
  - Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Source
  langs:
  - csharp
  - vb
  name: SemanticRetrieverConfig
  nameWithType: SemanticRetrieverConfig
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig
  type: Class
  source:
    id: SemanticRetrieverConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateAnswer/GenerateAnswerRequest.cs
    startLine: 67
  namespace: Glitch9.AIDevKit.Google
  summary: Configuration for retrieving grounding content from a Corpus or Document created using the Semantic Retriever API.
  example: []
  syntax:
    content: public class SemanticRetrieverConfig
    content.vb: Public Class SemanticRetrieverConfig
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Source
  commentId: P:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Source
  id: Source
  parent: Glitch9.AIDevKit.Google.SemanticRetrieverConfig
  langs:
  - csharp
  - vb
  name: Source
  nameWithType: SemanticRetrieverConfig.Source
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Source
  type: Property
  source:
    id: Source
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateAnswer/GenerateAnswerRequest.cs
    startLine: 73
  namespace: Glitch9.AIDevKit.Google
  summary: >-
    Required.

    Name of the resource for retrieval, e.g. corpora/123 or corpora/123/documents/abc.
  example: []
  syntax:
    content: public string Source { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Source As String
  overload: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Source*
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Query
  commentId: P:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Query
  id: Query
  parent: Glitch9.AIDevKit.Google.SemanticRetrieverConfig
  langs:
  - csharp
  - vb
  name: Query
  nameWithType: SemanticRetrieverConfig.Query
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Query
  type: Property
  source:
    id: Query
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateAnswer/GenerateAnswerRequest.cs
    startLine: 79
  namespace: Glitch9.AIDevKit.Google
  summary: >-
    Required.

    Query to use for similarity matching Chunks in the given resource.
  example: []
  syntax:
    content: public Content Query { get; set; }
    parameters: []
    return:
      type: Glitch9.AIDevKit.Google.Content
    content.vb: Public Property Query As Content
  overload: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Query*
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MetadataFilters
  commentId: P:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MetadataFilters
  id: MetadataFilters
  parent: Glitch9.AIDevKit.Google.SemanticRetrieverConfig
  langs:
  - csharp
  - vb
  name: MetadataFilters
  nameWithType: SemanticRetrieverConfig.MetadataFilters
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MetadataFilters
  type: Property
  source:
    id: MetadataFilters
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateAnswer/GenerateAnswerRequest.cs
    startLine: 85
  namespace: Glitch9.AIDevKit.Google
  summary: >-
    Optional.

    Filters for selecting Documents and/or Chunks from the resource.
  example: []
  syntax:
    content: public List<MetadataFilter> MetadataFilters { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Glitch9.AIDevKit.Google.MetadataFilter}
    content.vb: Public Property MetadataFilters As List(Of MetadataFilter)
  overload: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MetadataFilters*
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MaxChunksCount
  commentId: P:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MaxChunksCount
  id: MaxChunksCount
  parent: Glitch9.AIDevKit.Google.SemanticRetrieverConfig
  langs:
  - csharp
  - vb
  name: MaxChunksCount
  nameWithType: SemanticRetrieverConfig.MaxChunksCount
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MaxChunksCount
  type: Property
  source:
    id: MaxChunksCount
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateAnswer/GenerateAnswerRequest.cs
    startLine: 91
  namespace: Glitch9.AIDevKit.Google
  summary: >-
    Optional.

    Maximum number of relevant Chunks to retrieve.
  example: []
  syntax:
    content: public int MaxChunksCount { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxChunksCount As Integer
  overload: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MaxChunksCount*
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MinimumRelevanceScore
  commentId: P:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MinimumRelevanceScore
  id: MinimumRelevanceScore
  parent: Glitch9.AIDevKit.Google.SemanticRetrieverConfig
  langs:
  - csharp
  - vb
  name: MinimumRelevanceScore
  nameWithType: SemanticRetrieverConfig.MinimumRelevanceScore
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MinimumRelevanceScore
  type: Property
  source:
    id: MinimumRelevanceScore
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateAnswer/GenerateAnswerRequest.cs
    startLine: 97
  namespace: Glitch9.AIDevKit.Google
  summary: >-
    Optional.

    Minimum relevance score for retrieved relevant Chunks.
  example: []
  syntax:
    content: public float MinimumRelevanceScore { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property MinimumRelevanceScore As Single
  overload: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MinimumRelevanceScore*
references:
- uid: Glitch9.AIDevKit.Google
  commentId: N:Glitch9.AIDevKit.Google
  href: Glitch9.html
  name: Glitch9.AIDevKit.Google
  nameWithType: Glitch9.AIDevKit.Google
  fullName: Glitch9.AIDevKit.Google
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Source*
  commentId: Overload:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Source
  href: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.html#Glitch9_AIDevKit_Google_SemanticRetrieverConfig_Source
  name: Source
  nameWithType: SemanticRetrieverConfig.Source
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Source
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Query*
  commentId: Overload:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Query
  href: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.html#Glitch9_AIDevKit_Google_SemanticRetrieverConfig_Query
  name: Query
  nameWithType: SemanticRetrieverConfig.Query
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.Query
- uid: Glitch9.AIDevKit.Google.Content
  commentId: T:Glitch9.AIDevKit.Google.Content
  parent: Glitch9.AIDevKit.Google
  href: Glitch9.AIDevKit.Google.Content.html
  name: Content
  nameWithType: Content
  fullName: Glitch9.AIDevKit.Google.Content
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MetadataFilters*
  commentId: Overload:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MetadataFilters
  href: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.html#Glitch9_AIDevKit_Google_SemanticRetrieverConfig_MetadataFilters
  name: MetadataFilters
  nameWithType: SemanticRetrieverConfig.MetadataFilters
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MetadataFilters
- uid: System.Collections.Generic.List{Glitch9.AIDevKit.Google.MetadataFilter}
  commentId: T:System.Collections.Generic.List{Glitch9.AIDevKit.Google.MetadataFilter}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: Glitch9.AIDevKit.Google.MetadataFilter.html
  name: List<MetadataFilter>
  nameWithType: List<MetadataFilter>
  fullName: System.Collections.Generic.List<Glitch9.AIDevKit.Google.MetadataFilter>
  nameWithType.vb: List(Of MetadataFilter)
  fullName.vb: System.Collections.Generic.List(Of Glitch9.AIDevKit.Google.MetadataFilter)
  name.vb: List(Of MetadataFilter)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - uid: Glitch9.AIDevKit.Google.MetadataFilter
    name: MetadataFilter
    href: Glitch9.AIDevKit.Google.MetadataFilter.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Glitch9.AIDevKit.Google.MetadataFilter
    name: MetadataFilter
    href: Glitch9.AIDevKit.Google.MetadataFilter.html
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MaxChunksCount*
  commentId: Overload:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MaxChunksCount
  href: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.html#Glitch9_AIDevKit_Google_SemanticRetrieverConfig_MaxChunksCount
  name: MaxChunksCount
  nameWithType: SemanticRetrieverConfig.MaxChunksCount
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MaxChunksCount
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MinimumRelevanceScore*
  commentId: Overload:Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MinimumRelevanceScore
  href: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.html#Glitch9_AIDevKit_Google_SemanticRetrieverConfig_MinimumRelevanceScore
  name: MinimumRelevanceScore
  nameWithType: SemanticRetrieverConfig.MinimumRelevanceScore
  fullName: Glitch9.AIDevKit.Google.SemanticRetrieverConfig.MinimumRelevanceScore
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
