### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Mubert.MubertSettings
  commentId: T:Glitch9.AIDevKit.Mubert.MubertSettings
  id: MubertSettings
  parent: Glitch9.AIDevKit.Mubert
  children: []
  langs:
  - csharp
  - vb
  name: MubertSettings
  nameWithType: MubertSettings
  fullName: Glitch9.AIDevKit.Mubert.MubertSettings
  type: Class
  source:
    id: MubertSettings
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Common/Settings/MubertSettings.cs
    startLine: 5
  namespace: Glitch9.AIDevKit.Mubert
  syntax:
    content: >-
      [AssetPath("Resources/AIDevKit")]

      public class MubertSettings : AIClientSettings<MubertSettings>
    content.vb: >-
      <AssetPath("Resources/AIDevKit")>

      Public Class MubertSettings Inherits AIClientSettings(Of MubertSettings)
  inheritance:
  - System.Object
  - Glitch9.ScriptableObjects.ScriptableResource{Glitch9.AIDevKit.Mubert.MubertSettings}
  - Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}
  inheritedMembers:
  - Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.oldApiKey
  - Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.encryptedApiKey
  - Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.encryptApiKey
  - Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.apiKey
  - Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.GetApiKey
  - Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.HasApiKey
  - Glitch9.ScriptableObjects.ScriptableResource{Glitch9.AIDevKit.Mubert.MubertSettings}.Instance
  attributes:
  - type: Glitch9.AssetPathAttribute
    ctor: Glitch9.AssetPathAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Resources/AIDevKit
references:
- uid: Glitch9.AIDevKit.Mubert
  commentId: N:Glitch9.AIDevKit.Mubert
  href: Glitch9.html
  name: Glitch9.AIDevKit.Mubert
  nameWithType: Glitch9.AIDevKit.Mubert
  fullName: Glitch9.AIDevKit.Mubert
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Mubert
    name: Mubert
    href: Glitch9.AIDevKit.Mubert.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Mubert
    name: Mubert
    href: Glitch9.AIDevKit.Mubert.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Glitch9.ScriptableObjects.ScriptableResource{Glitch9.AIDevKit.Mubert.MubertSettings}
  commentId: T:Glitch9.ScriptableObjects.ScriptableResource{Glitch9.AIDevKit.Mubert.MubertSettings}
  parent: Glitch9.ScriptableObjects
  definition: Glitch9.ScriptableObjects.ScriptableResource`1
  href: Glitch9.AIDevKit.Mubert.MubertSettings.html
  name: ScriptableResource<MubertSettings>
  nameWithType: ScriptableResource<MubertSettings>
  fullName: Glitch9.ScriptableObjects.ScriptableResource<Glitch9.AIDevKit.Mubert.MubertSettings>
  nameWithType.vb: ScriptableResource(Of MubertSettings)
  fullName.vb: Glitch9.ScriptableObjects.ScriptableResource(Of Glitch9.AIDevKit.Mubert.MubertSettings)
  name.vb: ScriptableResource(Of MubertSettings)
  spec.csharp:
  - uid: Glitch9.ScriptableObjects.ScriptableResource`1
    name: ScriptableResource
  - name: <
  - uid: Glitch9.AIDevKit.Mubert.MubertSettings
    name: MubertSettings
    href: Glitch9.AIDevKit.Mubert.MubertSettings.html
  - name: '>'
  spec.vb:
  - uid: Glitch9.ScriptableObjects.ScriptableResource`1
    name: ScriptableResource
  - name: (
  - name: Of
  - name: " "
  - uid: Glitch9.AIDevKit.Mubert.MubertSettings
    name: MubertSettings
    href: Glitch9.AIDevKit.Mubert.MubertSettings.html
  - name: )
- uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}
  commentId: T:Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}
  parent: Glitch9.AIDevKit.Client
  definition: Glitch9.AIDevKit.Client.AIClientSettings`1
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html
  name: AIClientSettings<MubertSettings>
  nameWithType: AIClientSettings<MubertSettings>
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<Glitch9.AIDevKit.Mubert.MubertSettings>
  nameWithType.vb: AIClientSettings(Of MubertSettings)
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of Glitch9.AIDevKit.Mubert.MubertSettings)
  name.vb: AIClientSettings(Of MubertSettings)
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings`1
    name: AIClientSettings
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html
  - name: <
  - uid: Glitch9.AIDevKit.Mubert.MubertSettings
    name: MubertSettings
    href: Glitch9.AIDevKit.Mubert.MubertSettings.html
  - name: '>'
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings`1
    name: AIClientSettings
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: Glitch9.AIDevKit.Mubert.MubertSettings
    name: MubertSettings
    href: Glitch9.AIDevKit.Mubert.MubertSettings.html
  - name: )
- uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.oldApiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.oldApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}
  definition: Glitch9.AIDevKit.Client.AIClientSettings`1.oldApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_oldApiKey
  name: oldApiKey
  nameWithType: AIClientSettings<MubertSettings>.oldApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<Glitch9.AIDevKit.Mubert.MubertSettings>.oldApiKey
  nameWithType.vb: AIClientSettings(Of MubertSettings).oldApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of Glitch9.AIDevKit.Mubert.MubertSettings).oldApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.encryptedApiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.encryptedApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}
  definition: Glitch9.AIDevKit.Client.AIClientSettings`1.encryptedApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_encryptedApiKey
  name: encryptedApiKey
  nameWithType: AIClientSettings<MubertSettings>.encryptedApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<Glitch9.AIDevKit.Mubert.MubertSettings>.encryptedApiKey
  nameWithType.vb: AIClientSettings(Of MubertSettings).encryptedApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of Glitch9.AIDevKit.Mubert.MubertSettings).encryptedApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.encryptApiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.encryptApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}
  definition: Glitch9.AIDevKit.Client.AIClientSettings`1.encryptApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_encryptApiKey
  name: encryptApiKey
  nameWithType: AIClientSettings<MubertSettings>.encryptApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<Glitch9.AIDevKit.Mubert.MubertSettings>.encryptApiKey
  nameWithType.vb: AIClientSettings(Of MubertSettings).encryptApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of Glitch9.AIDevKit.Mubert.MubertSettings).encryptApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.apiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.apiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}
  definition: Glitch9.AIDevKit.Client.AIClientSettings`1.apiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_apiKey
  name: apiKey
  nameWithType: AIClientSettings<MubertSettings>.apiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<Glitch9.AIDevKit.Mubert.MubertSettings>.apiKey
  nameWithType.vb: AIClientSettings(Of MubertSettings).apiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of Glitch9.AIDevKit.Mubert.MubertSettings).apiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.GetApiKey
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.GetApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}
  definition: Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_GetApiKey
  name: GetApiKey()
  nameWithType: AIClientSettings<MubertSettings>.GetApiKey()
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<Glitch9.AIDevKit.Mubert.MubertSettings>.GetApiKey()
  nameWithType.vb: AIClientSettings(Of MubertSettings).GetApiKey()
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of Glitch9.AIDevKit.Mubert.MubertSettings).GetApiKey()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.GetApiKey
    name: GetApiKey
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_GetApiKey
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.GetApiKey
    name: GetApiKey
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_GetApiKey
  - name: (
  - name: )
- uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.HasApiKey
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.HasApiKey
  parent: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}
  definition: Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_HasApiKey
  name: HasApiKey()
  nameWithType: AIClientSettings<MubertSettings>.HasApiKey()
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<Glitch9.AIDevKit.Mubert.MubertSettings>.HasApiKey()
  nameWithType.vb: AIClientSettings(Of MubertSettings).HasApiKey()
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of Glitch9.AIDevKit.Mubert.MubertSettings).HasApiKey()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.HasApiKey
    name: HasApiKey
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_HasApiKey
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings{Glitch9.AIDevKit.Mubert.MubertSettings}.HasApiKey
    name: HasApiKey
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_HasApiKey
  - name: (
  - name: )
- uid: Glitch9.ScriptableObjects.ScriptableResource{Glitch9.AIDevKit.Mubert.MubertSettings}.Instance
  commentId: P:Glitch9.ScriptableObjects.ScriptableResource{Glitch9.AIDevKit.Mubert.MubertSettings}.Instance
  parent: Glitch9.ScriptableObjects.ScriptableResource{Glitch9.AIDevKit.Mubert.MubertSettings}
  definition: Glitch9.ScriptableObjects.ScriptableResource`1.Instance
  name: Instance
  nameWithType: ScriptableResource<MubertSettings>.Instance
  fullName: Glitch9.ScriptableObjects.ScriptableResource<Glitch9.AIDevKit.Mubert.MubertSettings>.Instance
  nameWithType.vb: ScriptableResource(Of MubertSettings).Instance
  fullName.vb: Glitch9.ScriptableObjects.ScriptableResource(Of Glitch9.AIDevKit.Mubert.MubertSettings).Instance
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.ScriptableObjects.ScriptableResource`1
  commentId: T:Glitch9.ScriptableObjects.ScriptableResource`1
  name: ScriptableResource<TSelf>
  nameWithType: ScriptableResource<TSelf>
  fullName: Glitch9.ScriptableObjects.ScriptableResource<TSelf>
  nameWithType.vb: ScriptableResource(Of TSelf)
  fullName.vb: Glitch9.ScriptableObjects.ScriptableResource(Of TSelf)
  name.vb: ScriptableResource(Of TSelf)
  spec.csharp:
  - uid: Glitch9.ScriptableObjects.ScriptableResource`1
    name: ScriptableResource
  - name: <
  - name: TSelf
  - name: '>'
  spec.vb:
  - uid: Glitch9.ScriptableObjects.ScriptableResource`1
    name: ScriptableResource
  - name: (
  - name: Of
  - name: " "
  - name: TSelf
  - name: )
- uid: Glitch9.ScriptableObjects
  commentId: N:Glitch9.ScriptableObjects
  href: Glitch9.html
  name: Glitch9.ScriptableObjects
  nameWithType: Glitch9.ScriptableObjects
  fullName: Glitch9.ScriptableObjects
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.ScriptableObjects
    name: ScriptableObjects
    href: Glitch9.ScriptableObjects.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.ScriptableObjects
    name: ScriptableObjects
    href: Glitch9.ScriptableObjects.html
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1
  commentId: T:Glitch9.AIDevKit.Client.AIClientSettings`1
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html
  name: AIClientSettings<TSelf>
  nameWithType: AIClientSettings<TSelf>
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>
  nameWithType.vb: AIClientSettings(Of TSelf)
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf)
  name.vb: AIClientSettings(Of TSelf)
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings`1
    name: AIClientSettings
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html
  - name: <
  - name: TSelf
  - name: '>'
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings`1
    name: AIClientSettings
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TSelf
  - name: )
- uid: Glitch9.AIDevKit.Client
  commentId: N:Glitch9.AIDevKit.Client
  href: Glitch9.html
  name: Glitch9.AIDevKit.Client
  nameWithType: Glitch9.AIDevKit.Client
  fullName: Glitch9.AIDevKit.Client
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Client
    name: Client
    href: Glitch9.AIDevKit.Client.html
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.oldApiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings`1.oldApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_oldApiKey
  name: oldApiKey
  nameWithType: AIClientSettings<TSelf>.oldApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.oldApiKey
  nameWithType.vb: AIClientSettings(Of TSelf).oldApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).oldApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.encryptedApiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings`1.encryptedApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_encryptedApiKey
  name: encryptedApiKey
  nameWithType: AIClientSettings<TSelf>.encryptedApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.encryptedApiKey
  nameWithType.vb: AIClientSettings(Of TSelf).encryptedApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).encryptedApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.encryptApiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings`1.encryptApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_encryptApiKey
  name: encryptApiKey
  nameWithType: AIClientSettings<TSelf>.encryptApiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.encryptApiKey
  nameWithType.vb: AIClientSettings(Of TSelf).encryptApiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).encryptApiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.apiKey
  commentId: F:Glitch9.AIDevKit.Client.AIClientSettings`1.apiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_apiKey
  name: apiKey
  nameWithType: AIClientSettings<TSelf>.apiKey
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.apiKey
  nameWithType.vb: AIClientSettings(Of TSelf).apiKey
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).apiKey
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_GetApiKey
  name: GetApiKey()
  nameWithType: AIClientSettings<TSelf>.GetApiKey()
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.GetApiKey()
  nameWithType.vb: AIClientSettings(Of TSelf).GetApiKey()
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).GetApiKey()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey
    name: GetApiKey
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_GetApiKey
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings`1.GetApiKey
    name: GetApiKey
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_GetApiKey
  - name: (
  - name: )
- uid: Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey
  commentId: M:Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey
  href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_HasApiKey
  name: HasApiKey()
  nameWithType: AIClientSettings<TSelf>.HasApiKey()
  fullName: Glitch9.AIDevKit.Client.AIClientSettings<TSelf>.HasApiKey()
  nameWithType.vb: AIClientSettings(Of TSelf).HasApiKey()
  fullName.vb: Glitch9.AIDevKit.Client.AIClientSettings(Of TSelf).HasApiKey()
  spec.csharp:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey
    name: HasApiKey
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_HasApiKey
  - name: (
  - name: )
  spec.vb:
  - uid: Glitch9.AIDevKit.Client.AIClientSettings`1.HasApiKey
    name: HasApiKey
    href: Glitch9.AIDevKit.Client.AIClientSettings-1.html#Glitch9_AIDevKit_Client_AIClientSettings_1_HasApiKey
  - name: (
  - name: )
- uid: Glitch9.ScriptableObjects.ScriptableResource`1.Instance
  commentId: P:Glitch9.ScriptableObjects.ScriptableResource`1.Instance
  name: Instance
  nameWithType: ScriptableResource<TSelf>.Instance
  fullName: Glitch9.ScriptableObjects.ScriptableResource<TSelf>.Instance
  nameWithType.vb: ScriptableResource(Of TSelf).Instance
  fullName.vb: Glitch9.ScriptableObjects.ScriptableResource(Of TSelf).Instance
