### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Google.FunctionCallingConfig
  commentId: T:Glitch9.AIDevKit.Google.FunctionCallingConfig
  id: FunctionCallingConfig
  parent: Glitch9.AIDevKit.Google
  children:
  - Glitch9.AIDevKit.Google.FunctionCallingConfig.AllowedFunctionNames
  - Glitch9.AIDevKit.Google.FunctionCallingConfig.Mode
  langs:
  - csharp
  - vb
  name: FunctionCallingConfig
  nameWithType: FunctionCallingConfig
  fullName: Glitch9.AIDevKit.Google.FunctionCallingConfig
  type: Class
  source:
    id: FunctionCallingConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/GenerateContentRequest.cs
    startLine: 370
  namespace: Glitch9.AIDevKit.Google
  summary: Configuration for specifying function calling behavior.
  example: []
  syntax:
    content: public class FunctionCallingConfig
    content.vb: Public Class FunctionCallingConfig
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.Google.FunctionCallingConfig.Mode
  commentId: P:Glitch9.AIDevKit.Google.FunctionCallingConfig.Mode
  id: Mode
  parent: Glitch9.AIDevKit.Google.FunctionCallingConfig
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: FunctionCallingConfig.Mode
  fullName: Glitch9.AIDevKit.Google.FunctionCallingConfig.Mode
  type: Property
  source:
    id: Mode
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/GenerateContentRequest.cs
    startLine: 377
  namespace: Glitch9.AIDevKit.Google
  summary: >-
    Required.

    Optional. Specifies the mode in which function calling should execute.

    If unspecified, the default value will be set to AUTO.
  example: []
  syntax:
    content: public Mode Mode { get; set; }
    parameters: []
    return:
      type: Glitch9.AIDevKit.Google.Mode
    content.vb: Public Property Mode As Mode
  overload: Glitch9.AIDevKit.Google.FunctionCallingConfig.Mode*
- uid: Glitch9.AIDevKit.Google.FunctionCallingConfig.AllowedFunctionNames
  commentId: P:Glitch9.AIDevKit.Google.FunctionCallingConfig.AllowedFunctionNames
  id: AllowedFunctionNames
  parent: Glitch9.AIDevKit.Google.FunctionCallingConfig
  langs:
  - csharp
  - vb
  name: AllowedFunctionNames
  nameWithType: FunctionCallingConfig.AllowedFunctionNames
  fullName: Glitch9.AIDevKit.Google.FunctionCallingConfig.AllowedFunctionNames
  type: Property
  source:
    id: AllowedFunctionNames
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/GenerateContentRequest.cs
    startLine: 390
  namespace: Glitch9.AIDevKit.Google
  summary: >-
    Optional.

    <p>

    A set of function names that, when provided, limits the functions the model will call.

    </p>

    <p>

    This should only be set when the Mode is ANY.

    Function names should match <xref href="Glitch9.AIDevKit.FunctionDeclaration.Name" data-throw-if-not-resolved="false"></xref>.

    With mode set to ANY, model will predict a function call from the set of function names provided.

    </p>
  example: []
  syntax:
    content: public List<string> AllowedFunctionNames { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public Property AllowedFunctionNames As List(Of String)
  overload: Glitch9.AIDevKit.Google.FunctionCallingConfig.AllowedFunctionNames*
references:
- uid: Glitch9.AIDevKit.Google
  commentId: N:Glitch9.AIDevKit.Google
  href: Glitch9.html
  name: Glitch9.AIDevKit.Google
  nameWithType: Glitch9.AIDevKit.Google
  fullName: Glitch9.AIDevKit.Google
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Google.FunctionCallingConfig.Mode*
  commentId: Overload:Glitch9.AIDevKit.Google.FunctionCallingConfig.Mode
  href: Glitch9.AIDevKit.Google.FunctionCallingConfig.html#Glitch9_AIDevKit_Google_FunctionCallingConfig_Mode
  name: Mode
  nameWithType: FunctionCallingConfig.Mode
  fullName: Glitch9.AIDevKit.Google.FunctionCallingConfig.Mode
- uid: Glitch9.AIDevKit.Google.Mode
  commentId: T:Glitch9.AIDevKit.Google.Mode
  parent: Glitch9.AIDevKit.Google
  href: Glitch9.AIDevKit.Google.Mode.html
  name: Mode
  nameWithType: Mode
  fullName: Glitch9.AIDevKit.Google.Mode
- uid: Glitch9.AIDevKit.FunctionDeclaration.Name
  commentId: P:Glitch9.AIDevKit.FunctionDeclaration.Name
  href: Glitch9.AIDevKit.FunctionDeclaration.html#Glitch9_AIDevKit_FunctionDeclaration_Name
  name: Name
  nameWithType: FunctionDeclaration.Name
  fullName: Glitch9.AIDevKit.FunctionDeclaration.Name
- uid: Glitch9.AIDevKit.Google.FunctionCallingConfig.AllowedFunctionNames*
  commentId: Overload:Glitch9.AIDevKit.Google.FunctionCallingConfig.AllowedFunctionNames
  href: Glitch9.AIDevKit.Google.FunctionCallingConfig.html#Glitch9_AIDevKit_Google_FunctionCallingConfig_AllowedFunctionNames
  name: AllowedFunctionNames
  nameWithType: FunctionCallingConfig.AllowedFunctionNames
  fullName: Glitch9.AIDevKit.Google.FunctionCallingConfig.AllowedFunctionNames
- uid: System.Collections.Generic.List{System.String}
  commentId: T:System.Collections.Generic.List{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<string>
  nameWithType: List<string>
  fullName: System.Collections.Generic.List<string>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - uid: System.String
    name: string
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
