### YamlMime:ManagedReference
items:
- uid: Glitch9.AIDevKit.Google.ToolConfig
  commentId: T:Glitch9.AIDevKit.Google.ToolConfig
  id: ToolConfig
  parent: Glitch9.AIDevKit.Google
  children:
  - Glitch9.AIDevKit.Google.ToolConfig.FunctionCallingConfig
  langs:
  - csharp
  - vb
  name: ToolConfig
  nameWithType: ToolConfig
  fullName: Glitch9.AIDevKit.Google.ToolConfig
  type: Class
  source:
    id: ToolConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/GenerateContentRequest.cs
    startLine: 358
  namespace: Glitch9.AIDevKit.Google
  summary: The Tool configuration containing parameters for specifying <xref href="Glitch9.AIDevKit.Google.Tool" data-throw-if-not-resolved="false"></xref> use in the request.
  example: []
  syntax:
    content: public class ToolConfig
    content.vb: Public Class ToolConfig
  inheritance:
  - System.Object
- uid: Glitch9.AIDevKit.Google.ToolConfig.FunctionCallingConfig
  commentId: P:Glitch9.AIDevKit.Google.ToolConfig.FunctionCallingConfig
  id: FunctionCallingConfig
  parent: Glitch9.AIDevKit.Google.ToolConfig
  langs:
  - csharp
  - vb
  name: FunctionCallingConfig
  nameWithType: ToolConfig.FunctionCallingConfig
  fullName: Glitch9.AIDevKit.Google.ToolConfig.FunctionCallingConfig
  type: Property
  source:
    id: FunctionCallingConfig
    path: E:/UnityProjects/Glitch9/AIDevKit-Unity6/Assets/Glitch9/AIDevKit/Runtime/Scripts/Google/Models/Models/GenerateContent/GenerateContentRequest.cs
    startLine: 364
  namespace: Glitch9.AIDevKit.Google
  summary: >-
    Optional.

    Function calling config.
  example: []
  syntax:
    content: public FunctionCallingConfig FunctionCallingConfig { get; set; }
    parameters: []
    return:
      type: Glitch9.AIDevKit.Google.FunctionCallingConfig
    content.vb: Public Property FunctionCallingConfig As FunctionCallingConfig
  overload: Glitch9.AIDevKit.Google.ToolConfig.FunctionCallingConfig*
references:
- uid: Glitch9.AIDevKit.Google.Tool
  commentId: T:Glitch9.AIDevKit.Google.Tool
  parent: Glitch9.AIDevKit.Google
  href: Glitch9.AIDevKit.Google.Tool.html
  name: Tool
  nameWithType: Tool
  fullName: Glitch9.AIDevKit.Google.Tool
- uid: Glitch9.AIDevKit.Google
  commentId: N:Glitch9.AIDevKit.Google
  href: Glitch9.html
  name: Glitch9.AIDevKit.Google
  nameWithType: Glitch9.AIDevKit.Google
  fullName: Glitch9.AIDevKit.Google
  spec.csharp:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
  spec.vb:
  - uid: Glitch9
    name: Glitch9
    href: Glitch9.html
  - name: .
  - uid: Glitch9.AIDevKit
    name: AIDevKit
    href: Glitch9.AIDevKit.html
  - name: .
  - uid: Glitch9.AIDevKit.Google
    name: Google
    href: Glitch9.AIDevKit.Google.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Glitch9.AIDevKit.Google.ToolConfig.FunctionCallingConfig*
  commentId: Overload:Glitch9.AIDevKit.Google.ToolConfig.FunctionCallingConfig
  href: Glitch9.AIDevKit.Google.ToolConfig.html#Glitch9_AIDevKit_Google_ToolConfig_FunctionCallingConfig
  name: FunctionCallingConfig
  nameWithType: ToolConfig.FunctionCallingConfig
  fullName: Glitch9.AIDevKit.Google.ToolConfig.FunctionCallingConfig
- uid: Glitch9.AIDevKit.Google.FunctionCallingConfig
  commentId: T:Glitch9.AIDevKit.Google.FunctionCallingConfig
  parent: Glitch9.AIDevKit.Google
  href: Glitch9.AIDevKit.Google.FunctionCallingConfig.html
  name: FunctionCallingConfig
  nameWithType: FunctionCallingConfig
  fullName: Glitch9.AIDevKit.Google.FunctionCallingConfig
