# .github/workflows/deploy.yml
name: Build and Deploy DocFX to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 커밋될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # DocFX가 사용하는 .NET SDK 버전

      - name: Install DocFX
        run: dotnet tool install -g docfx --version 2.74.1

      - name: Build DocFX
        run: docfx docfx.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
